#!/usr/bin/env python3
"""Goal Flight task-backlog store and mirror writer."""

from __future__ import annotations

import argparse
import contextlib
import datetime as dt
import hashlib
import html
import json
import os
from pathlib import Path
import re
import shutil
import stat
import subprocess
import sys
import tempfile
from typing import Any, Callable
from urllib.parse import quote


ROOT = Path(__file__).resolve().parent
LIST_TYPE = list
SCRIPTS = ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import goalflight_compat as fcntl  # noqa: E402

try:  # noqa: E402
    import goalflight_dispatch_states
    import goalflight_ledger
except Exception:  # pragma: no cover - import failures surface at runtime.
    goalflight_dispatch_states = None  # type: ignore[assignment]
    goalflight_ledger = None  # type: ignore[assignment]


CHECKER = ROOT / "scripts" / "check_tasks_mirror.js"
ITEM_SCHEMA_VERSION = 1
FAMILY_PREFIX_BY_KIND = {"task": "t", "bug": "b", "decision": "q"}
VALID_FAMILIES = {"t", "b", "q", "ADR"}
TASK_DISPATCH_STATES = {"working", "worker-finished", "worker-failed"}
ITEM_ID_RE = re.compile(r"\b((?:ADR|bp|[tbq])-\d+)\b", re.IGNORECASE)
RESUME_NOTES_RE = re.compile(r"^RESUME-NOTES-(\d{4}-\d{2}-\d{2})(?:-rev(\d+))?\.md$")
REVIEW_SEVERITY = {"P0": "critical", "P1": "high", "P2": "medium", "P3": "low"}
HARVEST_DRAFT_TAGS = ("draft", "harvest")
HARVEST_MANAGED_SOURCE_NAMES = {
    "task-decomposition.md",
    "tasks-done.md",
    "bugs-done.md",
    "tasks.jsonl",
    "tasks-data.js",
    "index.html",
    "questions-for-user.html",
    "current-activity.html",
    "ticket.html",
    "tickets.html",
    "gf.js",
}
HARVEST_GENERATED_HEADER = "Generated by `goalflight_task.py sync`"
HARVEST_PLACEHOLDER_TOKENS = {
    '<SC-xx, or "local-only">',
    "<swept @ `<SHA>` | pending>",
    "<one-line bug placeholder>",
    "<increment>",
    "<one-line outcome>",
    "<decision>",
    "<date>",
    "<SHA>",
}
HARVEST_PLACEHOLDER_PHRASES = (
    "Example open task - replace with your first real chunk.",
    "Example open task — replace with your first real chunk.",
)
CANNED_LIST_STATUSES = {
    "outstanding",
    "awaiting-review",
    "working",
    "delegated",
    "decision",
    "waiting",
    "done-reviewed",
}
RESERVED_LANES = {"deferred", "held"}
MARKDOWN_SECTIONS = (
    ("pending", "To do"),
    ("working", "In progress"),
    ("awaiting-review", "Awaiting review"),
    ("worker-failed", "Failed / needs attention"),
    ("waiting", "Waiting"),
)
STATUS_LABELS = {
    "pending": "to do",
    "working": "in progress",
    "awaiting-review": "awaiting review",
    "decision": "decision",
    "waiting": "waiting",
    "done-reviewed": "done reviewed",
    "worker-failed": "worker failed",
}


class TaskError(Exception):
    """User-facing task-store failure."""


def require_regular_or_absent(path: Path) -> bool:
    try:
        st = os.lstat(path)
    except FileNotFoundError:
        return False
    except OSError as exc:
        raise TaskError(f"{path}: cannot stat safely before open: {exc}") from exc
    if path.is_symlink() or not stat.S_ISREG(st.st_mode):
        raise TaskError(f"{path}: refusing to open non-regular file")
    return True


def require_regular_file(path: Path) -> None:
    if not require_regular_or_absent(path):
        raise TaskError(f"{path}: missing required regular file")


class FileLock:
    def __init__(self, path: Path):
        self.path = path
        self._fh = None

    def __enter__(self) -> "FileLock":
        self.path.parent.mkdir(parents=True, exist_ok=True)
        require_regular_or_absent(self.path)
        self._fh = self.path.open("a+", encoding="utf-8")
        fcntl.flock(self._fh, fcntl.LOCK_EX)
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        assert self._fh is not None
        fcntl.flock(self._fh, fcntl.LOCK_UN)
        self._fh.close()


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def _resolve_loose(path: Path) -> Path:
    return path.expanduser().resolve(strict=False)


def _strip_managed_worktree(path: Path) -> Path:
    resolved = _resolve_loose(path)
    parts = resolved.parts
    for index, part in enumerate(parts[:-2]):
        if part == ".claude" and parts[index + 1] == "worktrees":
            return _resolve_loose(Path(*parts[:index]))
    return resolved


def resolve_project_root(value: str | None = None) -> Path:
    explicit = value or os.environ.get("GOALFLIGHT_PROJECT_ROOT")
    if explicit:
        return _strip_managed_worktree(Path(explicit))

    cwd = Path.cwd()
    try:
        top = Path(
            subprocess.check_output(
                ["git", "rev-parse", "--show-toplevel"],
                cwd=str(cwd),
                text=True,
                stderr=subprocess.DEVNULL,
            ).strip()
        )
        common_raw = subprocess.check_output(
            ["git", "rev-parse", "--git-common-dir"],
            cwd=str(cwd),
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return _strip_managed_worktree(cwd)

    common = Path(common_raw)
    if not common.is_absolute():
        common = top / common
    if common.name == ".git":
        return _strip_managed_worktree(common.parent)
    return _strip_managed_worktree(top)


def _actor(args: argparse.Namespace) -> str:
    if getattr(args, "by", None):
        return args.by
    dispatch_id = os.environ.get("GOALFLIGHT_DISPATCH_ID")
    if dispatch_id:
        return f"worker:{dispatch_id}"
    return os.environ.get("GOALFLIGHT_TASK_ACTOR") or "controller"


def _audit(action: str, actor: str, **extra: Any) -> dict[str, Any]:
    entry: dict[str, Any] = {"at": utc_now(), "actor": actor, "action": action}
    entry.update({k: v for k, v in extra.items() if v not in (None, [], {})})
    return entry


def _append_audit(item: dict[str, Any], action: str, actor: str, **extra: Any) -> None:
    audit = item.setdefault("audit", [])
    if not isinstance(audit, LIST_TYPE):
        raise TaskError(f"item {item.get('id', '<unknown>')}: audit must be an array")
    audit.append(_audit(action, actor, **extra))


def _make_item(
    item_id: str,
    *,
    kind: str,
    title: str,
    actor: str,
    blocked_by: list[Any] | tuple[Any, ...] | None = None,
    links: list[Any] | tuple[Any, ...] | None = None,
    tags: list[Any] | tuple[Any, ...] | None = None,
    lane: str | None = None,
    audit_action: str = "new",
) -> dict[str, Any]:
    item = {
        "schema_version": ITEM_SCHEMA_VERSION,
        "id": item_id,
        "kind": kind,
        "title": title,
        "blocked_by": _dedupe_strs(blocked_by),
        "links": _dedupe_strs(links),
        "done": False,
        "tags": _dedupe_strs(tags),
        "created_at": utc_now(),
        "created_by": actor,
        "audit": [_audit(audit_action, actor)],
    }
    if lane is not None:
        item["lane"] = lane
    return item


def _canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _item_json_line(item: dict[str, Any]) -> str:
    return json.dumps(item, ensure_ascii=False, separators=(",", ":"))


def _items_jsonl(items: list[dict[str, Any]]) -> str:
    if not items:
        return ""
    return "".join(_item_json_line(item) + "\n" for item in items)


def _items_data_js(items: list[dict[str, Any]]) -> str:
    payload = _json_for_script(items)
    return (
        "// tasks-data.js - generated by goalflight_task.py; do not edit by hand.\n"
        "window.GF_ITEMS = "
        + payload
        + ";\n"
        "if (typeof module !== \"undefined\" && module.exports) { module.exports = window.GF_ITEMS; }\n"
    )


def _json_for_script(value: Any) -> str:
    payload = json.dumps(value, ensure_ascii=False, indent=2)
    return (
        payload.replace("&", "\\u0026")
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )


def _md_text(value: Any) -> str:
    text = str(value if value is not None else "")
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _id_lookup(items: list[dict[str, Any]]) -> dict[str, str]:
    return {str(item.get("id", "")).lower(): str(item.get("id", "")) for item in items if item.get("id")}


def _canonical_item_id(value: str, lookup: dict[str, str]) -> str:
    return lookup.get(value.lower(), value)


def _ticket_link(item_id: str) -> str:
    return f"[{_md_text(item_id)}](ticket.html?id={quote(item_id, safe='')})"


def _md_autolink_ids(value: Any, lookup: dict[str, str]) -> str:
    text = _md_text(value)
    return ITEM_ID_RE.sub(lambda match: _ticket_link(_canonical_item_id(match.group(1), lookup)), text)


def _md_value_link(value: Any, lookup: dict[str, str]) -> str:
    text = str(value if value is not None else "")
    if ITEM_ID_RE.fullmatch(text):
        return _ticket_link(_canonical_item_id(text, lookup))
    return _md_autolink_ids(text, lookup)


def _md_list(values: Any, lookup: dict[str, str]) -> str:
    if not isinstance(values, LIST_TYPE) or not values:
        return ""
    return ", ".join(_md_value_link(value, lookup) for value in values if value not in (None, ""))


def _dedupe_strs(values: list[Any] | tuple[Any, ...] | None) -> list[str]:
    out: list[str] = []
    for value in values or []:
        if value in (None, ""):
            continue
        text = str(value)
        if text not in out:
            out.append(text)
    return out


def _clean_markdown_title(value: str) -> str:
    text = value.strip()
    text = re.sub(r"^\[[ xX]\]\s+", "", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = text.replace("`", "")
    text = text.replace("**", "").replace("__", "")
    text = re.sub(r"\s+", " ", text)
    return text.strip(" -\t")


def _strip_markdown_wrappers(value: str) -> str:
    text = value.strip()
    pairs = ("**", "__", "~~", "`", "*", "_")
    while text:
        for marker in pairs:
            if len(text) > len(marker) * 2 and text.startswith(marker) and text.endswith(marker):
                text = text[len(marker) : -len(marker)].strip()
                break
        else:
            return text
    return text


def _harvest_title_key(value: Any) -> str:
    text = str(value or "").strip()
    text = re.sub(r"^#{1,6}\s+", "", text)
    text = re.sub(r"^\[[ xX]\]\s+", "", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = html.unescape(_strip_markdown_wrappers(text))
    return re.sub(r"\s+", " ", text).strip().lower()


def _placeholder_key(value: Any) -> str:
    text = html.unescape(str(value or ""))
    text = text.replace("`", "")
    return re.sub(r"\s+", " ", text).strip().lower()


def _harvest_has_placeholder(value: Any) -> bool:
    text = _placeholder_key(value)
    if not text:
        return False
    for phrase in HARVEST_PLACEHOLDER_PHRASES:
        if _placeholder_key(phrase) in text:
            return True
    for token in HARVEST_PLACEHOLDER_TOKENS:
        if _placeholder_key(token) in text:
            return True
    return False


def _is_top_level_state_source(path: Path, name: str | None = None) -> bool:
    return path.parent.name == "docs-private" and (name is None or path.name == name)


def _is_managed_harvest_source(path: Path) -> bool:
    return _is_top_level_state_source(path) and path.name in HARVEST_MANAGED_SOURCE_NAMES


def _history_has_source(text: str, rel: str) -> bool:
    needle = f"- Source: {rel}"
    return any(line.strip() == needle for line in text.splitlines())


def _append_history_entries(history: Path, current: str, entries: list[tuple[str, list[str]]]) -> None:
    lines: list[str] = []
    for _, entry in entries:
        lines.extend(entry)
    _atomic_write_text(history, current.rstrip() + "\n" + "\n".join(lines).rstrip() + "\n", prefix=".history-")


def _matches_state_skeleton_stub(path: Path, text: str) -> bool:
    template = ROOT / "templates" / "state-skeleton" / path.name
    if not template.is_file():
        return False
    try:
        return text == template.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def _skip_harvest_source(path: Path, text: str) -> bool:
    if _is_managed_harvest_source(path):
        return True
    if _is_top_level_state_source(path, "bug-backlog.md") and HARVEST_GENERATED_HEADER in text:
        return True
    return _matches_state_skeleton_stub(path, text)


def _norm_key(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "").strip().lower())


def _short_hash(parts: list[Any]) -> str:
    payload = "\x1f".join(str(part or "") for part in parts)
    return hashlib.sha1(payload.encode("utf-8")).hexdigest()[:16]


def _rel_source(project_root: Path, path: Path, line: int | None = None) -> str:
    try:
        rel = path.resolve(strict=False).relative_to(project_root.resolve(strict=False))
        text = rel.as_posix()
    except ValueError:
        text = path.as_posix()
    if line is not None and line > 0:
        return f"{text}:{line}"
    return text


def _section_rows(rows: list[dict[str, Any]], section: str) -> list[dict[str, Any]]:
    return [row for row in rows if row.get("derived_status") == section]


def _is_reserved_lane(row: dict[str, Any]) -> bool:
    return row.get("lane") in RESERVED_LANES


def _parse_jsonl(path: Path) -> tuple[list[dict[str, Any]], dict[str, int]]:
    if not require_regular_or_absent(path):
        return [], {}
    items: list[dict[str, Any]] = []
    lines_by_id: dict[str, int] = {}
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not raw.strip():
            continue
        try:
            obj = json.loads(raw)
        except json.JSONDecodeError as exc:
            raise TaskError(f"{path}:{lineno}: invalid JSON: {exc.msg}") from exc
        if not isinstance(obj, dict):
            raise TaskError(f"{path}:{lineno}: expected a JSON object")
        item_id = obj.get("id")
        if not isinstance(item_id, str) or not item_id:
            raise TaskError(f"{path}:{lineno}: missing string id")
        if "status" in obj:
            raise TaskError(f"{path}:{lineno}: top-level status key is forbidden")
        if "lane" in obj and not isinstance(obj["lane"], str):
            raise TaskError(f"{path}:{lineno}: item {item_id} lane must be a string")
        if item_id in lines_by_id:
            raise TaskError(f"{path}:{lineno}: duplicate id {item_id} (first seen on line {lines_by_id[item_id]})")
        lines_by_id[item_id] = lineno
        items.append(_migrate_item_for_read(obj))
    return items, lines_by_id


def _migrate_item_for_read(item: dict[str, Any]) -> dict[str, Any]:
    migrated = dict(item)
    legacy = "schema_version" not in migrated
    version = migrated.get("schema_version")
    if not isinstance(version, int) or version < 1:
        migrated["schema_version"] = ITEM_SCHEMA_VERSION
    migrated.setdefault("blocked_by", [])
    migrated.setdefault("links", [])
    migrated.setdefault("done", False)
    if legacy and migrated.get("done") is True and "done_reviewed" not in migrated:
        migrated["done_reviewed"] = True
    return migrated


def _validate_items_for_write(items: list[dict[str, Any]], source: str = "tasks.jsonl") -> None:
    seen: dict[str, int] = {}
    for lineno, item in enumerate(items, start=1):
        if not isinstance(item, dict):
            raise TaskError(f"{source}: line {lineno}: expected a JSON object")
        legacy = "schema_version" not in item
        item_id = item.get("id")
        if not isinstance(item_id, str) or not item_id:
            raise TaskError(f"{source}: line {lineno}: missing string id")
        if "status" in item:
            raise TaskError(f"{source}: line {lineno}: item {item_id} carries forbidden top-level status key")
        if "lane" in item and not isinstance(item["lane"], str):
            raise TaskError(f"{source}: line {lineno}: item {item_id} lane must be a string")
        if item_id in seen:
            raise TaskError(f"{source}: line {lineno}: duplicate id {item_id} (first seen on line {seen[item_id]})")
        seen[item_id] = lineno
        item.setdefault("blocked_by", [])
        item.setdefault("links", [])
        item.setdefault("done", False)
        if legacy and item.get("done") is True and "done_reviewed" not in item:
            item["done_reviewed"] = True
        item.setdefault("schema_version", ITEM_SCHEMA_VERSION)
        if not isinstance(item["blocked_by"], LIST_TYPE):
            raise TaskError(f"{source}: line {lineno}: item {item_id} blocked_by must be an array")
        if not isinstance(item["links"], LIST_TYPE):
            raise TaskError(f"{source}: line {lineno}: item {item_id} links must be an array")
        if not isinstance(item["schema_version"], int) or item["schema_version"] < 1:
            raise TaskError(f"{source}: line {lineno}: item {item_id} schema_version must be a positive integer")
        if "dispatches" in item and not isinstance(item["dispatches"], LIST_TYPE):
            raise TaskError(f"{source}: line {lineno}: item {item_id} dispatches must be an array")


def _fsync_dir(path: Path) -> None:
    try:
        fd = os.open(path, os.O_RDONLY)
    except OSError:
        return
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def _write_text_fsync(path: Path, text: str) -> None:
    with path.open("w", encoding="utf-8") as fh:
        fh.write(text)
        fh.flush()
        os.fsync(fh.fileno())


def _write_bytes_fsync(path: Path, data: bytes) -> None:
    with path.open("wb") as fh:
        fh.write(data)
        fh.flush()
        os.fsync(fh.fileno())


def _atomic_write_text(path: Path, text: str, *, prefix: str = ".tmp-") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=prefix, dir=str(path.parent))
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        tmp.replace(path)
        _fsync_dir(path.parent)
    except Exception:
        with contextlib.suppress(FileNotFoundError):
            tmp.unlink()
        raise


def _run_checker(directory: Path) -> None:
    node = shutil.which("node")
    if not node:
        raise TaskError("scripts/check_tasks_mirror.js: node not found; refusing to write without strict mirror validation")
    if not CHECKER.is_file():
        raise TaskError(f"{CHECKER}: missing strict mirror checker")
    proc = subprocess.run(
        [node, str(CHECKER), str(directory)],
        cwd=str(ROOT),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=30,
        check=False,
    )
    if proc.returncode != 0:
        msg = (proc.stderr or proc.stdout).strip() or f"checker exited {proc.returncode}"
        raise TaskError(msg)


def _parse_time(value: Any) -> dt.datetime:
    if not isinstance(value, str) or not value:
        return dt.datetime.min.replace(tzinfo=dt.timezone.utc)
    try:
        parsed = dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return dt.datetime.min.replace(tzinfo=dt.timezone.utc)
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt.timezone.utc)
    return parsed.astimezone(dt.timezone.utc)


def _record_sort_time(record: dict[str, Any]) -> dt.datetime:
    for key in ("ts", "updated_at", "ended_at", "started_at"):
        parsed = _parse_time(record.get(key))
        if parsed != dt.datetime.min.replace(tzinfo=dt.timezone.utc):
            return parsed
    return dt.datetime.min.replace(tzinfo=dt.timezone.utc)


def _record_terminal_state(record: dict[str, Any]) -> str:
    terminal = record.get("terminal_state")
    if isinstance(terminal, str) and terminal:
        return terminal
    if goalflight_ledger is not None:
        return str(goalflight_ledger.terminal_state_for(record.get("state"), record.get("reason") or record.get("error")))
    return "unknown"


def _record_task_ids(record: dict[str, Any]) -> list[str]:
    out: list[str] = []
    plural = record.get("task_ids")
    values = plural if isinstance(plural, LIST_TYPE) else ([plural] if isinstance(plural, str) else [])
    legacy = record.get("task_id")
    if isinstance(legacy, str):
        values = [legacy, *values]
    for value in values:
        if not isinstance(value, str):
            continue
        for part in value.split(","):
            task_id = part.strip()
            if task_id and task_id not in out:
                out.append(task_id)
    return out


def _dispatch_status_from_record(record: dict[str, Any], *, live: bool) -> str | None:
    raw_state = record.get("state")
    if isinstance(raw_state, str) and raw_state in TASK_DISPATCH_STATES:
        return raw_state
    terminal = _record_terminal_state(record)
    normalized = None
    if goalflight_dispatch_states is not None:
        normalized = goalflight_dispatch_states.normalize_dispatch_state(raw_state)

    if terminal == "complete" or normalized == "complete":
        return "worker-finished"
    if terminal not in {"", "unknown", None}:
        return "worker-failed"
    if isinstance(raw_state, str) and raw_state.startswith("blocked"):
        return "worker-failed"

    if live:
        if normalized in {"waiting", "starting", "running", "running_quiet"} or raw_state in {
            "queued",
            "waiting_capacity",
            "handshaking",
        }:
            if goalflight_ledger is not None:
                classification = goalflight_ledger.classify(record)
                if classification.startswith("stale_") or classification in {"unknown_no_pid", "watcher_stopped"}:
                    return "worker-failed"
            return "working"
        return "worker-failed"

    return None


def _status_snapshot_from_record(record: dict[str, Any]) -> dict[str, Any]:
    keys = (
        "dispatch_id",
        "agent",
        "shape",
        "state",
        "terminal_state",
        "reason",
        "outcome",
        "worker_pid",
        "worker_alive",
        "worker_still_alive",
        "stdout_path",
        "stderr_path",
        "status_path",
        "updated_at",
        "started_at",
        "ended_at",
    )
    return {key: record.get(key) for key in keys if record.get(key) not in (None, "", [], {})}


def _breadcrumb_from_record(record: dict[str, Any]) -> dict[str, Any]:
    state = (
        _dispatch_status_from_record(record, live=True)
        or _dispatch_status_from_record(record, live=False)
        or record.get("state")
    )
    ts = record.get("ended_at") or record.get("updated_at") or record.get("started_at") or utc_now()
    crumb: dict[str, Any] = {
        "dispatch_id": record.get("dispatch_id"),
        "agent": record.get("agent"),
        "log": record.get("stdout_path") or record.get("log"),
        "stdout_path": record.get("stdout_path"),
        "stderr_path": record.get("stderr_path"),
        "status_path": record.get("status_path"),
        "started_at": record.get("started_at"),
        "ended_at": record.get("ended_at"),
        "state": state,
        "ts": ts,
        "terminal_state": _record_terminal_state(record),
        "marker": record.get("marker"),
        "worker_pid": record.get("worker_pid"),
        "hostname": record.get("hostname"),
        "last_worker_state": record.get("last_worker_state") or _status_snapshot_from_record(record),
    }
    return {k: v for k, v in crumb.items() if v not in (None, "", [], {})}


def _breadcrumb_key(crumb: dict[str, Any]) -> str:
    marker = crumb.get("marker")
    marker_key = _canonical_json(marker) if isinstance(marker, dict) else str(marker or "")
    return "|".join(
        [
            str(crumb.get("dispatch_id") or ""),
            str(crumb.get("state") or ""),
            str(crumb.get("ts") or ""),
            marker_key,
        ]
    )


def _latest_dispatch_breadcrumb(item: dict[str, Any]) -> dict[str, Any] | None:
    dispatches = item.get("dispatches")
    if not isinstance(dispatches, LIST_TYPE):
        return None
    candidates = []
    for crumb in dispatches:
        if not isinstance(crumb, dict):
            continue
        if _dispatch_status_from_record(crumb, live=False):
            candidates.append(crumb)
    if not candidates:
        return None
    return sorted(candidates, key=_record_sort_time)[-1]


def _latest_breadcrumb(item: dict[str, Any], *, role: str | None = None) -> dict[str, Any] | None:
    dispatches = item.get("dispatches")
    if not isinstance(dispatches, LIST_TYPE):
        return None
    candidates = []
    for crumb in dispatches:
        if not isinstance(crumb, dict):
            continue
        if role is not None and crumb.get("role") != role:
            continue
        candidates.append(crumb)
    if not candidates:
        return None
    return sorted(candidates, key=_record_sort_time)[-1]


def _latest_review_breadcrumb(item: dict[str, Any]) -> dict[str, Any] | None:
    return _latest_breadcrumb(item, role="review")


def _iso_from_epoch(epoch: int) -> str | None:
    if epoch <= 0:
        return None
    return dt.datetime.fromtimestamp(epoch, tz=dt.timezone.utc).isoformat(timespec="seconds")


def _epoch_from_time(value: Any) -> int:
    parsed = _parse_time(value)
    if parsed == dt.datetime.min.replace(tzinfo=dt.timezone.utc):
        return 0
    return int(parsed.timestamp())


def _parse_since(value: str | None) -> int | None:
    if value in (None, ""):
        return None
    raw = str(value).strip()
    now = int(dt.datetime.now(dt.timezone.utc).timestamp())
    match = re.fullmatch(r"(\d+)([smhdw])", raw)
    if match:
        amount = int(match.group(1))
        multiplier = {"s": 1, "m": 60, "h": 3600, "d": 86400, "w": 604800}[match.group(2)]
        return now - amount * multiplier
    match = re.fullmatch(r"now([+-])(\d+)", raw)
    if match:
        delta = int(match.group(2))
        return now - delta if match.group(1) == "-" else now + delta
    if raw.isdigit():
        return int(raw)
    parsed = _parse_time(raw)
    if parsed == dt.datetime.min.replace(tzinfo=dt.timezone.utc):
        raise TaskError(f"invalid --since value {value!r}; use 1h, now-3600, epoch seconds, or an ISO timestamp")
    return int(parsed.timestamp())


def _item_query_epoch(item: dict[str, Any]) -> int:
    epochs = [_epoch_from_time(item.get("created_at"))]
    crumb = _latest_breadcrumb(item)
    if crumb:
        epochs.append(_epoch_from_time(crumb.get("ts") or crumb.get("ended_at") or crumb.get("updated_at") or crumb.get("started_at")))
    return max(epochs) if epochs else 0


def _item_dispatch_epoch(item: dict[str, Any]) -> int:
    crumb = _latest_dispatch_breadcrumb(item)
    if not crumb:
        return 0
    return _epoch_from_time(crumb.get("ts") or crumb.get("ended_at") or crumb.get("updated_at") or crumb.get("started_at"))


def _is_done_reviewed(item: dict[str, Any]) -> bool:
    if item.get("done_reviewed") is True:
        return True
    return item.get("kind") == "decision" and item.get("done") is True


def _matches_canned_status(row: dict[str, Any], status: str | None) -> bool:
    if not status:
        return True
    if status == "outstanding":
        return not _is_done_reviewed(row)
    if status == "awaiting-review":
        return not _is_done_reviewed(row) and row.get("derived_status") == "awaiting-review"
    if status == "working":
        return not _is_done_reviewed(row) and row.get("derived_status") == "working"
    if status == "decision":
        return not _is_done_reviewed(row) and row.get("derived_status") == "decision"
    if status == "waiting":
        return not _is_done_reviewed(row) and row.get("derived_status") == "waiting"
    if status == "delegated":
        return _latest_dispatch_breadcrumb(row) is not None
    if status == "done-reviewed":
        return _is_done_reviewed(row)
    raise TaskError(f"unknown list status {status!r}; expected one of {', '.join(sorted(CANNED_LIST_STATUSES))}")


def _coerce_query(query: Any = None, **overrides: Any) -> dict[str, Any]:
    if query is None:
        out: dict[str, Any] = {}
    elif isinstance(query, str):
        out = {"status": query}
    elif isinstance(query, dict):
        out = dict(query)
    else:
        raise TaskError("query must be None, a canned status string, or a dict")
    out.update({k: v for k, v in overrides.items() if v not in (None, [], {})})
    blocked_by = out.get("blocked_by")
    if isinstance(blocked_by, str):
        out["blocked_by"] = _split_csv([blocked_by])
    elif isinstance(blocked_by, LIST_TYPE):
        values: list[str] = []
        for value in blocked_by:
            if isinstance(value, str):
                values.extend(_split_csv([value]))
        out["blocked_by"] = values
    status = out.get("status")
    if status not in (None, "") and status not in CANNED_LIST_STATUSES:
        raise TaskError(f"unknown list status {status!r}; expected one of {', '.join(sorted(CANNED_LIST_STATUSES))}")
    if out.get("since") not in (None, ""):
        out["since_epoch"] = _parse_since(str(out["since"]))
    return out


class TaskStore:
    def __init__(self, project_root: Path):
        self.project_root = _strip_managed_worktree(project_root)
        self.docs_dir = self.project_root / "docs-private"
        self.tasks_path = self.docs_dir / "tasks.jsonl"
        self.data_js_path = self.docs_dir / "tasks-data.js"
        self.task_decomposition_path = self.docs_dir / "task-decomposition.md"
        self.tasks_done_path = self.docs_dir / "tasks-done.md"
        self.bug_backlog_path = self.docs_dir / "bug-backlog.md"
        self.bugs_done_path = self.docs_dir / "bugs-done.md"
        self.store_lock_path = self.docs_dir / "tasks.lock"
        self.seq_path = self.docs_dir / ".task-seq"
        self.seq_lock_path = self.docs_dir / ".task-seq.lock"
        self.publish_marker_path = self.docs_dir / ".tasks-publish-incomplete.json"
        self.log_dir = self.docs_dir / "log"

    @contextlib.contextmanager
    def store_lock(self):
        self.docs_dir.mkdir(parents=True, exist_ok=True)
        with FileLock(self.store_lock_path):
            yield

    def load_items(self, *, recover_publish: bool = True) -> list[dict[str, Any]]:
        if recover_publish:
            self._recover_interrupted_publish()
        items, _ = _parse_jsonl(self.tasks_path)
        return items

    def items_by_id(self) -> dict[str, dict[str, Any]]:
        return {item["id"]: item for item in self.load_items()}

    def reserve_id(self, family: str) -> str:
        if family not in VALID_FAMILIES:
            raise TaskError(f"unknown id family {family!r}; expected one of {', '.join(sorted(VALID_FAMILIES))}")
        self.docs_dir.mkdir(parents=True, exist_ok=True)
        with FileLock(self.seq_lock_path):
            seq = self._read_seq()
            current = max(int(seq.get(family, 0)), self._max_existing_sequence(family))
            next_value = current + 1
            seq[family] = next_value
            tmp = self.seq_path.with_suffix(".tmp")
            tmp.write_text(json.dumps(seq, indent=2, sort_keys=True) + "\n", encoding="utf-8")
            tmp.replace(self.seq_path)
        return f"ADR-{next_value:03d}" if family == "ADR" else f"{family}-{next_value:03d}"

    def _max_existing_sequence(self, family: str) -> int:
        prefix = "ADR-" if family == "ADR" else f"{family}-"
        max_seen = 0
        for item in self.load_items():
            item_id = item.get("id")
            if not isinstance(item_id, str) or not item_id.startswith(prefix):
                continue
            suffix = item_id.removeprefix(prefix)
            if suffix.isdigit():
                max_seen = max(max_seen, int(suffix))
        return max_seen

    def _read_seq(self) -> dict[str, int]:
        if not require_regular_or_absent(self.seq_path):
            return {}
        text = self.seq_path.read_text(encoding="utf-8").strip()
        if not text:
            return {}
        if text.isdigit():
            return {"t": int(text)}
        try:
            raw = json.loads(text)
        except json.JSONDecodeError as exc:
            raise TaskError(f"{self.seq_path}:1: invalid JSON: {exc.msg}") from exc
        if not isinstance(raw, dict):
            raise TaskError(f"{self.seq_path}:1: expected a JSON object")
        out: dict[str, int] = {}
        for key, value in raw.items():
            if key not in VALID_FAMILIES:
                raise TaskError(f"{self.seq_path}:1: unknown id family {key!r}")
            if not isinstance(value, int) or value < 0:
                raise TaskError(f"{self.seq_path}:1: family {key!r} must be a non-negative integer")
            out[key] = value
        return out

    def mutate_items(self, update: Callable[[list[dict[str, Any]]], Any], *, allow_invalid_live_mirror: bool = False) -> Any:
        with self.store_lock():
            self._recover_interrupted_publish_locked()
            self._snapshot_last_good(require_valid=not allow_invalid_live_mirror)
            items = self.load_items(recover_publish=False)
            result = update(items)
            self.save_items_atomic(items)
            return result

    def save_items_atomic(self, items: list[dict[str, Any]]) -> None:
        self.docs_dir.mkdir(parents=True, exist_ok=True)
        _validate_items_for_write(items)
        staging = Path(tempfile.mkdtemp(prefix=".tasks-stage-", dir=str(self.docs_dir)))
        try:
            self._write_staged_generation(staging, items)
            _run_checker(staging)
            targets = {
                self.tasks_path: staging / "tasks.jsonl",
                self.data_js_path: staging / "tasks-data.js",
                self.task_decomposition_path: staging / "task-decomposition.md",
                self.tasks_done_path: staging / "tasks-done.md",
                self.bug_backlog_path: staging / "bug-backlog.md",
                self.bugs_done_path: staging / "bugs-done.md",
            }
            old_bytes = {path: path.read_bytes() if require_regular_or_absent(path) else None for path in targets}
            generation = hashlib.sha256((staging / "tasks.jsonl").read_bytes()).hexdigest()
            self._write_publish_marker(generation)
            try:
                for target, source in targets.items():
                    source.replace(target)
                _fsync_dir(self.docs_dir)
            except OSError:
                for target, data in old_bytes.items():
                    self._restore_bytes(target, data)
                self._clear_publish_marker()
                raise
            self._clear_publish_marker()
        finally:
            shutil.rmtree(staging, ignore_errors=True)

    @staticmethod
    def _restore_bytes(path: Path, data: bytes | None) -> None:
        if data is None:
            with contextlib.suppress(FileNotFoundError):
                path.unlink()
            _fsync_dir(path.parent)
            return
        tmp = path.with_suffix(path.suffix + ".restore")
        _write_bytes_fsync(tmp, data)
        tmp.replace(path)
        _fsync_dir(path.parent)

    def _write_staged_generation(self, staging: Path, items: list[dict[str, Any]]) -> None:
        _write_text_fsync(staging / "tasks.jsonl", _items_jsonl(items))
        _write_text_fsync(staging / "tasks-data.js", _items_data_js(self._mirror_items_for_script(items)))
        for name, content in self.generated_markdown(items).items():
            _write_text_fsync(staging / name, content)
        _fsync_dir(staging)

    def _mirror_items_for_script(self, items: list[dict[str, Any]]) -> list[dict[str, Any]]:
        rows = self.derived_rows_for_items(items)
        rows_by_id = {row["id"]: row for row in rows}
        mirrored: list[dict[str, Any]] = []
        for item in items:
            out = dict(item)
            derived = rows_by_id.get(item["id"], {}).get("derived_status")
            if isinstance(derived, str) and derived:
                out["derived_status"] = derived
            mirrored.append(out)
        return mirrored

    def _write_publish_marker(self, generation: str) -> None:
        marker = {
            "schema": "goalflight.tasks.publish.v1",
            "generation": generation,
            "canonical": "tasks.jsonl",
            "artifacts": [
                "tasks.jsonl",
                "tasks-data.js",
                "task-decomposition.md",
                "tasks-done.md",
                "bug-backlog.md",
                "bugs-done.md",
            ],
        }
        _write_text_fsync(self.publish_marker_path, json.dumps(marker, ensure_ascii=False, sort_keys=True) + "\n")
        _fsync_dir(self.docs_dir)

    def _clear_publish_marker(self) -> None:
        with contextlib.suppress(FileNotFoundError):
            self.publish_marker_path.unlink()
        _fsync_dir(self.docs_dir)

    def _recover_interrupted_publish(self) -> None:
        if not require_regular_or_absent(self.publish_marker_path):
            return
        with self.store_lock():
            self._recover_interrupted_publish_locked()

    def _recover_interrupted_publish_locked(self) -> None:
        if not require_regular_or_absent(self.publish_marker_path):
            return
        if not require_regular_or_absent(self.tasks_path):
            raise TaskError(f"{self.publish_marker_path}: interrupted task publish cannot recover because tasks.jsonl is missing")
        items, _ = _parse_jsonl(self.tasks_path)
        _validate_items_for_write(items)
        staging = Path(tempfile.mkdtemp(prefix=".tasks-repair-", dir=str(self.docs_dir)))
        try:
            self._write_staged_generation(staging, items)
            _run_checker(staging)
            for target, source in {
                self.tasks_path: staging / "tasks.jsonl",
                self.data_js_path: staging / "tasks-data.js",
                self.task_decomposition_path: staging / "task-decomposition.md",
                self.tasks_done_path: staging / "tasks-done.md",
                self.bug_backlog_path: staging / "bug-backlog.md",
                self.bugs_done_path: staging / "bugs-done.md",
            }.items():
                source.replace(target)
            _fsync_dir(self.docs_dir)
            self._clear_publish_marker()
        finally:
            shutil.rmtree(staging, ignore_errors=True)

    def _snapshot_last_good(self, *, require_valid: bool = True) -> None:
        tasks_exists = require_regular_or_absent(self.tasks_path)
        data_exists = require_regular_or_absent(self.data_js_path)
        if not tasks_exists and not data_exists:
            return
        if not tasks_exists or not data_exists:
            if not require_valid and tasks_exists:
                return
            raise TaskError(f"{self.docs_dir}: missing tasks.jsonl or tasks-data.js; refusing mutation without a valid last-known-good pair")
        try:
            _run_checker(self.docs_dir)
        except TaskError:
            if require_valid:
                raise
            return
        self.log_dir.mkdir(parents=True, exist_ok=True)
        stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
        require_regular_file(self.tasks_path)
        require_regular_file(self.data_js_path)
        shutil.copy2(self.tasks_path, self.log_dir / f"tasks-{stamp}.jsonl")
        shutil.copy2(self.data_js_path, self.log_dir / f"tasks-data-{stamp}.js")
        self._prune_backups()

    def _prune_backups(self, keep: int = 20) -> None:
        for pattern in ("tasks-*.jsonl", "tasks-data-*.js"):
            backups = sorted(self.log_dir.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
            for path in backups[keep:]:
                with contextlib.suppress(OSError):
                    path.unlink()

    def project_ledger_records(self) -> list[dict[str, Any]]:
        if goalflight_ledger is None:
            return []
        target = _strip_managed_worktree(self.project_root)
        records = []
        for record in goalflight_ledger.read_records():
            if not _record_task_ids(record):
                continue
            raw_root = record.get("project_root")
            if not isinstance(raw_root, str) or not raw_root:
                continue
            if _strip_managed_worktree(Path(raw_root)) == target:
                records.append(record)
        return records

    def _records_by_task(self) -> dict[str, list[dict[str, Any]]]:
        records_by_task: dict[str, list[dict[str, Any]]] = {}
        for record in self.project_ledger_records():
            for task_id in _record_task_ids(record):
                records_by_task.setdefault(task_id, []).append(record)
        return records_by_task

    def sync_dispatch_breadcrumbs(self, items: list[dict[str, Any]], actor: str) -> int:
        by_id = {item["id"]: item for item in items}
        changed = 0
        for record in self.project_ledger_records():
            dispatch_id = record.get("dispatch_id")
            if not isinstance(dispatch_id, str):
                continue
            crumb = _breadcrumb_from_record(record)
            for task_id in _record_task_ids(record):
                item = by_id.get(task_id)
                if item is None:
                    continue
                dispatches = item.setdefault("dispatches", [])
                if not isinstance(dispatches, LIST_TYPE):
                    raise TaskError(f"item {task_id}: dispatches must be an array")
                existing_keys = {
                    _breadcrumb_key(entry)
                    for entry in dispatches
                    if isinstance(entry, dict)
                }
                if _breadcrumb_key(crumb) in existing_keys:
                    continue
                dispatches.append(crumb)
                changed += 1
                _append_audit(item, "dispatch-sync", actor, dispatch_id=dispatch_id, state=crumb.get("state"))
        return changed

    def append_dispatch_breadcrumbs(self, task_ids: list[str], breadcrumb: dict[str, Any], actor: str) -> int:
        clean_ids = []
        for task_id in task_ids:
            if isinstance(task_id, str) and task_id and task_id not in clean_ids:
                clean_ids.append(task_id)
        if not clean_ids:
            return 0
        dispatch_id = breadcrumb.get("dispatch_id")
        if not isinstance(dispatch_id, str) or not dispatch_id:
            raise TaskError("dispatch breadcrumb requires dispatch_id")
        state = breadcrumb.get("state")
        if not isinstance(state, str) or state not in TASK_DISPATCH_STATES:
            raise TaskError(f"dispatch breadcrumb requires state in {sorted(TASK_DISPATCH_STATES)}")
        crumb = {k: v for k, v in dict(breadcrumb).items() if v not in (None, "", [], {})}
        crumb.setdefault("ts", utc_now())

        def update(items: list[dict[str, Any]]) -> int:
            by_id = {item["id"]: item for item in items}
            changed = 0
            for task_id in clean_ids:
                item = by_id.get(task_id)
                if item is None:
                    raise TaskError(f"{self.tasks_path}: item not found: {task_id}")
                dispatches = item.setdefault("dispatches", [])
                if not isinstance(dispatches, LIST_TYPE):
                    raise TaskError(f"item {task_id}: dispatches must be an array")
                dispatches.append(dict(crumb))
                changed += 1
                _append_audit(item, "dispatch-breadcrumb", actor, dispatch_id=dispatch_id, state=state)
            return changed

        return self.mutate_items(update, allow_invalid_live_mirror=True)

    def derived_rows(self) -> list[dict[str, Any]]:
        return self.derived_rows_for_items(self.load_items())

    def derived_rows_for_items(self, items: list[dict[str, Any]]) -> list[dict[str, Any]]:
        records_by_task = self._records_by_task()
        by_id = {item["id"]: item for item in items}
        rows = []
        for item in items:
            item_id = item["id"]
            row = dict(item)
            row["derived_status"] = self._derive_status(item, records_by_task.get(item_id, []), by_id)
            row["query_epoch"] = _item_query_epoch(row)
            query_time = _iso_from_epoch(row["query_epoch"])
            if query_time:
                row["query_time"] = query_time
            rows.append(row)
        return rows

    def get_item(self, item_id: str) -> dict[str, Any]:
        for row in self.derived_rows():
            if row.get("id") == item_id:
                return row
        raise TaskError(f"{self.tasks_path}: item not found: {item_id}")

    def query_items(self, query: Any = None, **overrides: Any) -> list[dict[str, Any]]:
        q = _coerce_query(query, **overrides)
        rows = self.derived_rows()
        status = q.get("status")
        kind = q.get("kind")
        blockers = q.get("blocked_by") or []
        since_epoch = q.get("since_epoch")

        def matches(row: dict[str, Any]) -> bool:
            if status and not _matches_canned_status(row, status):
                return False
            if kind and row.get("kind", "task") != kind:
                return False
            if blockers:
                row_blockers = row.get("blocked_by")
                if not isinstance(row_blockers, LIST_TYPE) or any(blocker not in row_blockers for blocker in blockers):
                    return False
            filter_epoch = _item_dispatch_epoch(row) if status == "delegated" else int(row.get("query_epoch") or 0)
            if since_epoch is not None and filter_epoch < int(since_epoch):
                return False
            return True

        return [row for row in rows if matches(row)]

    def _derive_status(
        self,
        item: dict[str, Any],
        live_records: list[dict[str, Any]],
        by_id: dict[str, dict[str, Any]],
    ) -> str:
        if _is_done_reviewed(item):
            return "done-reviewed"
        candidates: list[tuple[dt.datetime, str]] = []
        if live_records:
            for record in live_records:
                status = _dispatch_status_from_record(record, live=True)
                if status:
                    candidates.append((_record_sort_time(record), status))
        crumb = _latest_dispatch_breadcrumb(item)
        if crumb:
            status = _dispatch_status_from_record(crumb, live=False)
            if status:
                candidates.append((_record_sort_time(crumb), status))
        if item.get("done") is True:
            candidates.append((_record_sort_time({"ts": item.get("done_at") or item.get("closed_at") or item.get("created_at")}), "awaiting-review"))
        if candidates:
            latest = sorted(candidates, key=lambda row: row[0])[-1][1]
            return "awaiting-review" if latest == "worker-finished" else latest
        if item.get("kind") == "decision":
            return "decision"
        blockers = item.get("blocked_by")
        if isinstance(blockers, LIST_TYPE) and blockers:
            unresolved = any(not _is_done_reviewed(by_id.get(str(blocker), {})) for blocker in blockers)
            if unresolved:
                return "waiting"
        return "pending"

    def generated_markdown(self, items: list[dict[str, Any]]) -> dict[str, str]:
        rows = self.derived_rows_for_items(items)
        lookup = _id_lookup(items)
        tasks = [row for row in rows if row.get("kind", "task") == "task"]
        bugs = [row for row in rows if row.get("kind") == "bug"]
        return {
            "task-decomposition.md": self._render_task_decomposition(tasks, lookup),
            "tasks-done.md": self._render_tasks_done(tasks, lookup),
            "bug-backlog.md": self._render_bug_backlog(bugs, lookup),
            "bugs-done.md": self._render_bugs_done(bugs, lookup),
        }

    def _render_header(self, title: str) -> list[str]:
        return [
            f"# {title}",
            "",
            "> Generated by `goalflight_task.py sync` from `tasks.jsonl` plus the project dispatch ledger. Do not edit by hand.",
            "> Section authority: `protocols/progress-dashboard.md`.",
            "",
        ]

    def _render_item_block(self, row: dict[str, Any], lookup: dict[str, str], *, done_view: bool = False) -> list[str]:
        item_id = str(row.get("id", ""))
        lines = [f"### {item_id}", "", f"**{_md_autolink_ids(row.get('title', '(untitled)'), lookup)}**", ""]
        if row.get("derived_status") and not done_view:
            lines.append(f"- Status: {_md_text(STATUS_LABELS.get(str(row['derived_status']), row['derived_status']))}")
        blockers = _md_list(row.get("blocked_by"), lookup)
        if blockers:
            lines.append(f"- Blocked by: {blockers}")
        links = _md_list(row.get("links"), lookup)
        if links:
            lines.append(f"- Links: {links}")
        for key, label in (
            ("lane", "Lane"),
            ("severity", "Severity"),
            ("pattern", "Pattern"),
            ("source", "Source"),
            ("acceptance", "Acceptance"),
            ("prompt_path", "Prompt"),
        ):
            value = row.get(key)
            if isinstance(value, str) and value:
                lines.append(f"- {label}: {_md_autolink_ids(value, lookup)}")
        if isinstance(row.get("prompt"), str) and row["prompt"]:
            lines.extend(["- Prompt:", ""])
            lines.extend(f"  {line}" if line else "" for line in _md_text(row["prompt"]).splitlines())
        lines.append("")
        return lines

    def _render_sections(
        self,
        rows: list[dict[str, Any]],
        lookup: dict[str, str],
        sections: tuple[tuple[str, str], ...],
        *,
        empty: str,
    ) -> list[str]:
        lines: list[str] = []
        any_rows = False
        for key, label in sections:
            lines.extend([f"## {label}", ""])
            section = _section_rows(rows, key)
            if section:
                any_rows = True
                for row in section:
                    lines.extend(self._render_item_block(row, lookup))
            else:
                lines.extend([empty, ""])
        if not any_rows and not rows:
            return [empty, ""]
        return lines

    def _render_lane_backlog(self, rows: list[dict[str, Any]], lookup: dict[str, str]) -> list[str]:
        backlog = [
            row
            for row in rows
            if row.get("derived_status") != "done-reviewed" and _is_reserved_lane(row)
        ]
        if not backlog:
            return []
        lines = ["## Backlog", ""]
        for row in backlog:
            lines.extend(self._render_item_block(row, lookup))
        return lines

    def _render_task_decomposition(self, tasks: list[dict[str, Any]], lookup: dict[str, str]) -> str:
        open_tasks = [
            row
            for row in tasks
            if row.get("derived_status") != "done-reviewed" and not _is_reserved_lane(row)
        ]
        lines = self._render_header("goal-flight — Task Decomposition")
        lines.extend(self._render_sections(open_tasks, lookup, MARKDOWN_SECTIONS, empty="_(none)_"))
        lines.extend(self._render_lane_backlog(tasks, lookup))
        return "\n".join(lines).rstrip() + "\n"

    def _render_tasks_done(self, tasks: list[dict[str, Any]], lookup: dict[str, str]) -> str:
        done = [row for row in tasks if row.get("derived_status") == "done-reviewed"]
        lines = self._render_header("goal-flight — Tasks Done")
        lines.extend(["## Done", ""])
        if done:
            for row in reversed(done):
                lines.extend(self._render_item_block(row, lookup, done_view=True))
        else:
            lines.extend(["_(none)_", ""])
        return "\n".join(lines).rstrip() + "\n"

    def _render_bug_backlog(self, bugs: list[dict[str, Any]], lookup: dict[str, str]) -> str:
        open_bugs = [
            row
            for row in bugs
            if row.get("derived_status") != "done-reviewed" and not _is_reserved_lane(row)
        ]
        lines = self._render_header("goal-flight — Bug Backlog")
        lines.extend(self._render_sections(open_bugs, lookup, MARKDOWN_SECTIONS, empty="_(none)_"))
        lines.extend(self._render_lane_backlog(bugs, lookup))
        return "\n".join(lines).rstrip() + "\n"

    def _render_bugs_done(self, bugs: list[dict[str, Any]], lookup: dict[str, str]) -> str:
        done = [row for row in bugs if row.get("derived_status") == "done-reviewed"]
        lines = self._render_header("goal-flight — Bugs Done")
        lines.extend(["## Done", ""])
        if done:
            for row in reversed(done):
                lines.extend(self._render_item_block(row, lookup, done_view=True))
        else:
            lines.extend(["_(none)_", ""])
        return "\n".join(lines).rstrip() + "\n"


def _kind_from_reference(value: str, default: str) -> str:
    lower = value.lower()
    if lower.startswith(("b-", "bp-")):
        return "bug"
    if lower.startswith(("q-", "adr-")):
        return "decision"
    if lower.startswith("t-"):
        return "task"
    return default


def _harvest_candidate(
    store: TaskStore,
    *,
    kind: str,
    title: str,
    source_path: Path,
    source_type: str,
    line: int | None = None,
    severity: str | None = None,
    pattern: str | None = None,
) -> dict[str, Any] | None:
    clean_title = _clean_markdown_title(title)
    if not clean_title or clean_title.lower() in {"none", "(none)"}:
        return None
    if _harvest_has_placeholder(clean_title):
        return None
    source_ref = _rel_source(store.project_root, source_path, line)
    source_file = _rel_source(store.project_root, source_path)
    tags = [*HARVEST_DRAFT_TAGS, source_type]
    if pattern:
        tags.append(pattern)
    candidate: dict[str, Any] = {
        "kind": kind,
        "title": clean_title,
        "links": [source_ref],
        "tags": tags,
        "source": "harvest",
        "source_ref": source_ref,
        "harvest_source": source_type,
        "harvest_key": f"harvest:{_short_hash([kind, _harvest_title_key(clean_title), source_file, source_type])}",
    }
    if severity:
        candidate["severity"] = severity
    if pattern:
        candidate["pattern"] = pattern
    return candidate


def _append_candidate(candidates: list[dict[str, Any]], candidate: dict[str, Any] | None) -> None:
    if candidate is None:
        return
    key = candidate.get("harvest_key")
    if key and any(existing.get("harvest_key") == key for existing in candidates):
        return
    title_key = (str(candidate.get("kind", "task")), _harvest_title_key(candidate.get("title")))
    if title_key[1] and any((str(existing.get("kind", "task")), _harvest_title_key(existing.get("title"))) == title_key for existing in candidates):
        return
    candidates.append(candidate)


def _block_is_open(block: dict[str, Any]) -> bool:
    status = _norm_key(block.get("status"))
    return status not in {"done", "done-reviewed", "closed", "fixed"}


def _harvest_heading_blocks(
    store: TaskStore,
    path: Path,
    *,
    default_kind: str,
    source_type: str,
) -> list[dict[str, Any]]:
    if not require_regular_or_absent(path):
        return []
    candidates: list[dict[str, Any]] = []
    current: dict[str, Any] | None = None

    def flush() -> None:
        nonlocal current
        if not current:
            return
        if not _block_is_open(current):
            current = None
            return
        title = current.get("title") or current.get("heading") or ""
        ref = str(current.get("ref") or "")
        _append_candidate(
            candidates,
            _harvest_candidate(
                store,
                kind=_kind_from_reference(ref, default_kind),
                title=str(title),
                source_path=path,
                source_type=source_type,
                line=int(current.get("line") or 0),
            ),
        )
        current = None

    text = path.read_text(encoding="utf-8", errors="replace")
    if _skip_harvest_source(path, text):
        return []
    lines = text.splitlines()
    for lineno, line in enumerate(lines, start=1):
        heading = re.match(r"^#{2,6}\s+((?:ADR|bp|[tbq])-\d+)\b(?:\s+(.+))?", line, re.IGNORECASE)
        if heading:
            flush()
            current = {
                "ref": heading.group(1),
                "heading": heading.group(2) or heading.group(1),
                "line": lineno,
            }
            continue
        if current is None:
            list_item = re.match(r"^\s*(?:[-*]\s+|\d+[.)]\s+)(?:\[[ xX]\]\s+)?(.+?)\s*$", line)
            if list_item and "Status:" not in list_item.group(1) and not _harvest_has_placeholder(list_item.group(1)):
                _append_candidate(
                    candidates,
                    _harvest_candidate(
                        store,
                        kind=default_kind,
                        title=list_item.group(1),
                        source_path=path,
                        source_type=source_type,
                        line=lineno,
                    ),
                )
            continue
        bold = re.search(r"\*\*(.+?)\*\*", line)
        if bold and not current.get("title"):
            current["title"] = bold.group(1)
        status = re.match(r"^\s*[-*]\s+Status:\s*(.+?)\s*$", line, re.IGNORECASE)
        if status:
            current["status"] = status.group(1)
    flush()
    return candidates


def _harvest_review_candidates(store: TaskStore) -> list[dict[str, Any]]:
    review_dir = store.docs_dir / "reviews"
    if not review_dir.is_dir():
        return []
    candidates: list[dict[str, Any]] = []
    for path in sorted(review_dir.rglob("*.md")):
        rel_lower = path.relative_to(review_dir).as_posix().lower()
        if "backlog" not in rel_lower and "finding" not in rel_lower:
            continue
        require_regular_file(path)
        text = path.read_text(encoding="utf-8", errors="replace")
        if _skip_harvest_source(path, text):
            continue
        lines = text.splitlines()
        for lineno, line in enumerate(lines, start=1):
            if _harvest_has_placeholder(line):
                continue
            bold = re.search(r"\*\*(.+?)\*\*", line)
            if not bold:
                continue
            text = _clean_markdown_title(bold.group(1))
            match = re.match(r"^(P[0-3]|critical|high|medium|low)\b\s*(?:[-:\u2014]\s*)?(.*)$", text, re.IGNORECASE)
            if not match:
                continue
            severity_token = match.group(1).upper()
            title = match.group(2).strip() or text
            severity = REVIEW_SEVERITY.get(severity_token, severity_token.lower())
            _append_candidate(
                candidates,
                _harvest_candidate(
                    store,
                    kind="bug",
                    title=title,
                    source_path=path,
                    source_type="review-finding",
                    line=lineno,
                    severity=severity,
                ),
            )
    return candidates


def _resume_sort_key(path: Path) -> tuple[str, int, str]:
    match = RESUME_NOTES_RE.match(path.name)
    if not match:
        return ("0000-00-00", 0, path.name)
    return (match.group(1), int(match.group(2) or 0), path.name)


def _newest_resume_note(docs_dir: Path) -> Path | None:
    notes = sorted(docs_dir.glob("RESUME-NOTES-*.md"), key=_resume_sort_key)
    return notes[-1] if notes else None


def _harvest_resume_candidates(store: TaskStore) -> list[dict[str, Any]]:
    path = _newest_resume_note(store.docs_dir)
    if path is None:
        return []
    require_regular_file(path)
    text = path.read_text(encoding="utf-8", errors="replace")
    if _skip_harvest_source(path, text):
        return []
    candidates: list[dict[str, Any]] = []
    section: str | None = None
    for lineno, line in enumerate(text.splitlines(), start=1):
        heading = re.match(r"^#{2,6}\s+(.+?)\s*$", line)
        if heading:
            title = _norm_key(heading.group(1))
            if any(key in title for key in ("next action", "current goal", "remaining")):
                section = "task"
            elif "do not re-litigate" in title:
                section = "decision"
            else:
                section = None
            continue
        if section is None:
            continue
        list_item = re.match(r"^\s*(?:[-*]\s+|\d+[.)]\s+)(?:\[[ xX]\]\s+)?(.+?)\s*$", line)
        if not list_item:
            continue
        text = list_item.group(1)
        if _harvest_has_placeholder(text):
            continue
        kind = "decision" if section == "decision" else "task"
        _append_candidate(
            candidates,
            _harvest_candidate(
                store,
                kind=kind,
                title=text,
                source_path=path,
                source_type=f"resume-{section}",
                line=lineno,
            ),
        )
    return candidates


def _collect_harvest_candidates(store: TaskStore) -> list[dict[str, Any]]:
    candidates: list[dict[str, Any]] = []
    bug_paths = [
        store.docs_dir / "bug-backlog.md",
        *store.docs_dir.glob("bug-pattern*.md"),
        *store.docs_dir.glob("bug-patterns/*.md"),
    ]
    for path in sorted(bug_paths):
        candidates.extend(_harvest_heading_blocks(store, path, default_kind="bug", source_type="bug-backlog"))
    candidates.extend(_harvest_review_candidates(store))
    candidates.extend(_harvest_resume_candidates(store))
    deduped: list[dict[str, Any]] = []
    for candidate in candidates:
        _append_candidate(deduped, candidate)
    return deduped


def _existing_harvest_keys(items: list[dict[str, Any]]) -> tuple[set[str], set[tuple[str, str]]]:
    keys: set[str] = set()
    titles: set[tuple[str, str]] = set()
    for item in items:
        key = item.get("harvest_key")
        if isinstance(key, str) and key:
            keys.add(key)
        kind = str(item.get("kind", "task"))
        title = _harvest_title_key(item.get("title"))
        if title:
            titles.add((kind, title))
    return keys, titles


def _add_harvest_candidates(store: TaskStore, items: list[dict[str, Any]], actor: str, candidates: list[dict[str, Any]]) -> dict[str, Any]:
    existing_keys, existing_titles = _existing_harvest_keys(items)
    created: list[str] = []
    skipped = 0
    for candidate in candidates:
        key = str(candidate.get("harvest_key") or "")
        title_key = (str(candidate.get("kind", "task")), _harvest_title_key(candidate.get("title")))
        if (key and key in existing_keys) or title_key in existing_titles:
            skipped += 1
            continue
        item_id = store.reserve_id(FAMILY_PREFIX_BY_KIND[str(candidate["kind"])])
        item = _make_item(
            item_id,
            kind=str(candidate["kind"]),
            title=str(candidate["title"]),
            actor=actor,
            links=LIST_TYPE(candidate.get("links") or []),
            tags=LIST_TYPE(candidate.get("tags") or HARVEST_DRAFT_TAGS),
        )
        for field in ("source", "source_ref", "harvest_source", "harvest_key", "severity", "pattern"):
            value = candidate.get(field)
            if value not in (None, "", [], {}):
                item[field] = value
        _append_audit(item, "harvest", actor, source_ref=item.get("source_ref"), harvest_source=item.get("harvest_source"))
        items.append(item)
        created.append(item_id)
        if key:
            existing_keys.add(key)
        existing_titles.add(title_key)
    return {"created": created, "skipped": skipped, "candidates": len(candidates)}


def _first_resume_paragraph(lines: list[str], heading: str) -> str:
    active = False
    buf: list[str] = []
    for line in lines:
        header = re.match(r"^#{2,6}\s+(.+?)\s*$", line)
        if header:
            if active and buf:
                break
            active = _norm_key(header.group(1)) == _norm_key(heading)
            continue
        if not active:
            continue
        if not line.strip():
            if buf:
                break
            continue
        if line.lstrip().startswith(("-", "*")):
            continue
        buf.append(_clean_markdown_title(line))
    return " ".join(buf).strip()


def _first_resume_next(lines: list[str]) -> str:
    active = False
    for line in lines:
        header = re.match(r"^#{2,6}\s+(.+?)\s*$", line)
        if header:
            active = "next action" in _norm_key(header.group(1))
            continue
        if not active:
            continue
        item = re.match(r"^\s*(?:[-*]\s+|\d+[.)]\s+)(?:\[[ xX]\]\s+)?(.+?)\s*$", line)
        if item:
            return _clean_markdown_title(item.group(1))
    return ""


def _append_resume_history(store: TaskStore, actor: str) -> list[str]:
    notes = sorted(store.docs_dir.glob("RESUME-NOTES-*.md"), key=_resume_sort_key)
    if not notes:
        return []
    history = store.docs_dir / "history.md"
    existing = history.read_text(encoding="utf-8") if require_regular_or_absent(history) else (
        "# goal-flight - History (write-once)\n\n"
        "> Append-only. One entry per compaction handoff. Never edit prior entries.\n"
        "> Living state: newest `RESUME-NOTES-*.md`.\n"
    )
    by_date: dict[str, list[Path]] = {}
    for path in notes:
        date, _, _ = _resume_sort_key(path)
        by_date.setdefault(date, []).append(path)
    additions: list[tuple[str, list[str]]] = []
    for path in notes:
        require_regular_file(path)
        rel = _rel_source(store.project_root, path)
        if _history_has_source(existing, rel) or any(rel == entry_rel for entry_rel, _ in additions):
            continue
        date, rev, _ = _resume_sort_key(path)
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        summary = _first_resume_paragraph(lines, "TL;DR") or _clean_markdown_title(lines[0] if lines else path.stem)
        next_action = _first_resume_next(lines)
        superseded = [
            _rel_source(store.project_root, old)
            for old in by_date.get(date, [])
            if old != path and _resume_sort_key(old)[1] < rev
        ]
        entry = ["", f"## {date} - {path.name}", "", f"- Source: {rel}"]
        if summary:
            entry.append(f"- Summary: {summary[:280]}")
        if next_action:
            entry.append(f"- Next: {next_action[:220]}")
        if superseded:
            entry.append(f"- Supersedes: {', '.join(superseded)}")
        entry.append(f"- Harvested by: {actor}")
        additions.append((rel, entry))
    appended: list[str] = []
    if additions:
        with store.store_lock():
            current = history.read_text(encoding="utf-8") if require_regular_or_absent(history) else existing
            missing = [(rel, entry) for rel, entry in additions if not _history_has_source(current, rel)]
            if missing:
                _append_history_entries(history, current, missing)
                appended = [rel for rel, _ in missing]
    return appended


def _review_bug_key(item_id: str, dispatch_id: str, title: str) -> str:
    return f"review-bug:{_short_hash([item_id, dispatch_id, _norm_key(title)])}"


def _split_csv(values: list[str] | None) -> list[str]:
    out: list[str] = []
    for value in values or []:
        for part in value.split(","):
            part = part.strip()
            if part:
                out.append(part)
    return out


def _create_item(store: TaskStore, args: argparse.Namespace, actor: str) -> str:
    """Reserve an id and append a new item from args. Shared by `new` and `capture`."""
    family = args.id_family or FAMILY_PREFIX_BY_KIND[args.kind]
    item_id = store.reserve_id(family)

    def update(items: list[dict[str, Any]]) -> str:
        if any(item.get("id") == item_id for item in items):
            raise TaskError(f"{store.tasks_path}: id {item_id} already exists; .task-seq is stale")
        item = _make_item(
            item_id,
            kind=args.kind,
            title=args.title,
            actor=actor,
            blocked_by=_split_csv(args.blocked_by),
            links=_split_csv(args.links),
            tags=_split_csv(args.tags),
            lane=args.lane,
        )
        for key in ("acceptance", "prompt", "prompt_path", "pattern", "severity", "source"):
            value = getattr(args, key, None)
            if value not in (None, "", [], {}):
                item[key] = value
        items.append(item)
        return item_id

    return store.mutate_items(update)


def _cmd_new(store: TaskStore, args: argparse.Namespace) -> int:
    created = _create_item(store, args, _actor(args))
    if args.json:
        print(json.dumps({"id": created}, sort_keys=True))
    else:
        print(created)
    return 0


def _cmd_capture(store: TaskStore, args: argparse.Namespace) -> int:
    # Reflex defaults for the zero-flag common path (`capture "<what>"`): a task
    # parked in the deferred backlog, sourced to the cwd. --severity implies a bug.
    if getattr(args, "kind", None) is None:
        args.kind = "bug" if getattr(args, "severity", None) else "task"
    if not getattr(args, "lane", None):
        args.lane = "deferred"
    if not getattr(args, "source", None):
        args.source = os.getcwd()
    created = _create_item(store, args, _actor(args))
    if args.json:
        print(json.dumps({"id": created}, sort_keys=True))
    else:
        print(created)
    # One next-step hint to STDERR (keeps stdout / `--json | jq` clean; never an interrupt).
    print(
        f"captured {created} ({args.lane}). promote: goalflight_task.py lane {created} <name>",
        file=sys.stderr,
    )
    return 0


def _cmd_show(store: TaskStore, args: argparse.Namespace) -> int:
    item = store.get_item(args.item_id)
    if args.prompt:
        prompt = item.get("prompt")
        if isinstance(prompt, str):
            print(prompt)
            return 0
        prompt_path = item.get("prompt_path")
        if isinstance(prompt_path, str) and prompt_path:
            path = Path(prompt_path)
            if not path.is_absolute():
                path = store.project_root / path
            require_regular_file(path)
            print(path.read_text(encoding="utf-8"), end="")
            return 0
        raise TaskError(f"{args.item_id}: no prompt or prompt_path")
    if args.json:
        print(json.dumps(item, ensure_ascii=False, sort_keys=True))
    else:
        print(json.dumps(item, indent=2, ensure_ascii=False, sort_keys=True))
    return 0


def _cmd_block(store: TaskStore, args: argparse.Namespace) -> int:
    blockers = _split_csv(args.on)
    if not blockers:
        raise TaskError("block: --on requires at least one blocker id")
    actor = _actor(args)

    def update(items: list[dict[str, Any]]) -> None:
        by_id = {item["id"]: item for item in items}
        item = by_id.get(args.item_id)
        if item is None:
            raise TaskError(f"{store.tasks_path}: item not found: {args.item_id}")
        blocked_by = item.setdefault("blocked_by", [])
        if not isinstance(blocked_by, LIST_TYPE):
            raise TaskError(f"item {args.item_id}: blocked_by must be an array")
        for blocker in blockers:
            if blocker not in blocked_by:
                blocked_by.append(blocker)
        _append_audit(item, "block", actor, on=blockers)

    store.mutate_items(update)
    print(args.item_id)
    return 0


def _cmd_unblock(store: TaskStore, args: argparse.Namespace) -> int:
    actor = _actor(args)
    remove = set(_split_csv(args.on))

    def update(items: list[dict[str, Any]]) -> None:
        by_id = {item["id"]: item for item in items}
        item = by_id.get(args.item_id)
        if item is None:
            raise TaskError(f"{store.tasks_path}: item not found: {args.item_id}")
        blocked_by = item.setdefault("blocked_by", [])
        if not isinstance(blocked_by, LIST_TYPE):
            raise TaskError(f"item {args.item_id}: blocked_by must be an array")
        item["blocked_by"] = [value for value in blocked_by if remove and value not in remove] if remove else []
        _append_audit(item, "unblock", actor, on=sorted(remove) if remove else None)

    store.mutate_items(update)
    print(args.item_id)
    return 0


def _cmd_lane(store: TaskStore, args: argparse.Namespace) -> int:
    actor = _actor(args)

    def update(items: list[dict[str, Any]]) -> None:
        by_id = {item["id"]: item for item in items}
        item = by_id.get(args.item_id)
        if item is None:
            raise TaskError(f"{store.tasks_path}: item not found: {args.item_id}")
        old_lane = item.get("lane")
        item["lane"] = args.lane
        _append_audit(item, "lane", actor, old_lane=old_lane if isinstance(old_lane, str) else None, lane=args.lane)

    store.mutate_items(update)
    print(args.item_id)
    return 0


def _cmd_done(store: TaskStore, args: argparse.Namespace) -> int:
    actor = _actor(args)

    def update(items: list[dict[str, Any]]) -> None:
        by_id = {item["id"]: item for item in items}
        item = by_id.get(args.item_id)
        if item is None:
            raise TaskError(f"{store.tasks_path}: item not found: {args.item_id}")
        if item.get("done") is True:
            raise TaskError(f"{args.item_id}: already done")
        if item.get("blocked_by") and not args.force:
            raise TaskError(f"{args.item_id}: blocked_by is non-empty; use --force to close anyway")
        item["done"] = True
        item["done_at"] = utc_now()
        item["done_by"] = actor
        item.setdefault("closed_at", item["done_at"])
        item.setdefault("closed_by", actor)
        item["resolution"] = args.resolution
        _append_audit(item, "done", actor, resolution=args.resolution)

    store.mutate_items(update)
    print(args.item_id)
    return 0


def _cmd_review(store: TaskStore, args: argparse.Namespace) -> int:
    actor = _actor(args)
    bug_titles = _dedupe_strs(getattr(args, "bugs", []))
    if bug_titles and args.verdict != "findings":
        raise TaskError("review --bug requires --verdict findings")
    if bug_titles and not args.bug_pattern:
        raise TaskError("review --bug requires --bug-pattern <minted-pattern-id>")
    crumb: dict[str, Any] = {
        "dispatch_id": args.dispatch,
        "role": "review",
        "verdict": args.verdict,
        "findings_ref": args.findings,
        "ts": utc_now(),
    }

    def update(items: list[dict[str, Any]]) -> dict[str, Any]:
        by_id = {item["id"]: item for item in items}
        item = by_id.get(args.item_id)
        if item is None:
            raise TaskError(f"{store.tasks_path}: item not found: {args.item_id}")
        dispatches = item.setdefault("dispatches", [])
        if not isinstance(dispatches, LIST_TYPE):
            raise TaskError(f"item {args.item_id}: dispatches must be an array")
        review_crumb = {k: v for k, v in crumb.items() if v not in (None, "", [], {})}
        dispatches.append(review_crumb)
        _append_audit(item, "review", actor, dispatch_id=args.dispatch, verdict=args.verdict, findings_ref=args.findings)
        existing_keys = {
            value
            for value in (existing.get("review_bug_key") for existing in items)
            if isinstance(value, str) and value
        }
        created_bugs: list[str] = []
        skipped_bugs = 0
        for title in bug_titles:
            key = _review_bug_key(args.item_id, args.dispatch, title)
            if key in existing_keys:
                skipped_bugs += 1
                continue
            bug_id = store.reserve_id("b")
            links = [args.item_id]
            if args.findings:
                links.append(args.findings)
            bug = _make_item(
                bug_id,
                kind="bug",
                title=title,
                actor=actor,
                links=links,
                tags=["review-finding", args.bug_pattern, *_split_csv(args.bug_tags)],
            )
            bug["source"] = "review"
            bug["pattern"] = args.bug_pattern
            if args.bug_severity:
                bug["severity"] = args.bug_severity
            bug["review_item_id"] = args.item_id
            bug["review_dispatch_id"] = args.dispatch
            bug["review_breadcrumb_key"] = _breadcrumb_key(review_crumb)
            bug["review_bug_key"] = key
            if args.findings:
                bug["review_findings_ref"] = args.findings
            _append_audit(bug, "review-bug-capture", actor, review_dispatch_id=args.dispatch, pattern=args.bug_pattern)
            items.append(bug)
            existing_keys.add(key)
            created_bugs.append(bug_id)
        return {"item_id": args.item_id, "bugs": created_bugs, "skipped_bugs": skipped_bugs}

    result = store.mutate_items(update, allow_invalid_live_mirror=True)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, sort_keys=True))
    else:
        print(args.item_id)
        for bug_id in result["bugs"]:
            print(bug_id)
    return 0


def _cmd_harvest(store: TaskStore, args: argparse.Namespace) -> int:
    actor = _actor(args)
    candidates = _collect_harvest_candidates(store)
    if args.dry_run:
        payload = {"created": [], "skipped": 0, "candidates": len(candidates), "history_added": [], "drafts": candidates}
        print(json.dumps(payload, ensure_ascii=False, sort_keys=True) if args.json else "\n".join(str(item["title"]) for item in candidates))
        return 0

    def update(items: list[dict[str, Any]]) -> dict[str, Any]:
        return _add_harvest_candidates(store, items, actor, candidates)

    result = store.mutate_items(update, allow_invalid_live_mirror=True)
    result["history_added"] = [] if args.no_history else _append_resume_history(store, actor)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, sort_keys=True))
    else:
        print(f"OK: harvest created {len(result['created'])} draft items ({result['skipped']} skipped, {len(result['history_added'])} history entries)")
    return 0


def _cmd_accept(store: TaskStore, args: argparse.Namespace) -> int:
    actor = _actor(args)

    def update(items: list[dict[str, Any]]) -> None:
        rows = store.derived_rows_for_items(items)
        by_id = {row["id"]: row for row in rows}
        row = by_id.get(args.item_id)
        if row is None:
            raise TaskError(f"{store.tasks_path}: item not found: {args.item_id}")
        if _is_done_reviewed(row):
            raise TaskError(f"{args.item_id}: already done-reviewed")
        if row.get("derived_status") != "awaiting-review":
            raise TaskError(f"{args.item_id}: not DONE/awaiting-review; run task done or wait for worker completion first")
        review = _latest_review_breadcrumb(row)
        if not review:
            raise TaskError(f"{args.item_id}: no logged review; run task review before accept")
        if review.get("verdict") != "clean":
            raise TaskError(f"{args.item_id}: latest review verdict is {review.get('verdict')!r}, not clean")

        item = next(item for item in items if item.get("id") == args.item_id)
        item["done"] = True
        item["done_reviewed"] = True
        item["done_reviewed_at"] = utc_now()
        item["done_reviewed_by"] = actor
        item["closed_at"] = item["done_reviewed_at"]
        item["closed_by"] = actor
        item["accepted_review_dispatch_id"] = review.get("dispatch_id")
        if review.get("findings_ref"):
            item["accepted_review_findings_ref"] = review.get("findings_ref")
        _append_audit(item, "accept", actor, review_dispatch_id=review.get("dispatch_id"))

    store.mutate_items(update, allow_invalid_live_mirror=True)
    print(args.item_id)
    return 0


def _cmd_list(store: TaskStore, args: argparse.Namespace) -> int:
    rows = store.query_items(
        {
            "status": args.status,
            "kind": args.kind,
            "blocked_by": args.blocked_by,
            "since": args.since,
        }
    )
    if args.json:
        print(json.dumps(rows, ensure_ascii=False, sort_keys=True))
        return 0
    for row in rows:
        print(f"{row['id']} {row['derived_status']} {row.get('title', '')}")
    return 0


def _cmd_status(store: TaskStore, args: argparse.Namespace) -> int:
    rows = store.derived_rows()
    if args.json:
        payload = {"project_root": str(store.project_root), "items": rows}
        print(json.dumps(payload, ensure_ascii=False, sort_keys=True))
        return 0
    for row in rows:
        print(f"{row['id']} {row['derived_status']} {row.get('title', '')}")
    return 0


def _cmd_sync(store: TaskStore, args: argparse.Namespace) -> int:
    actor = _actor(args)

    def update(items: list[dict[str, Any]]) -> int:
        return store.sync_dispatch_breadcrumbs(items, actor)

    changed = store.mutate_items(update, allow_invalid_live_mirror=True)
    print(f"OK: synced tasks-data.js and generated markdown views ({changed} dispatch breadcrumb updates)")
    return 0


def _api_store(project_root: str | Path | None = None) -> TaskStore:
    return TaskStore(resolve_project_root(str(project_root) if project_root is not None else None))


def get(item_id: str, project_root: str | Path | None = None) -> dict[str, Any]:
    """Read one item by id with derived status and schema migration applied."""
    return _api_store(project_root).get_item(item_id)


def list(query: Any = None, project_root: str | Path | None = None, **filters: Any) -> list[dict[str, Any]]:  # noqa: A001
    """Query items with the same row shape emitted by `goalflight_task.py list --json`."""
    return _api_store(project_root).query_items(query, **filters)


def outstanding(project_root: str | Path | None = None, **filters: Any) -> list[dict[str, Any]]:
    """Return all items that are not DONE-REVIEWED."""
    return list("outstanding", project_root=project_root, **filters)


def build_parser() -> argparse.ArgumentParser:
    examples = """common forms:
  CAPTURE:
    goalflight_task.py capture "Investigate flaky test"        # reflex: task, lane=deferred
    goalflight_task.py new "Tighten review gate" --kind task --prompt-path docs-private/briefs/t-014.md
    goalflight_task.py new "Park follow-up" --lane deferred
  READ:
    goalflight_task.py show t-014 --json
    goalflight_task.py list outstanding
    goalflight_task.py list delegated --since 1h --json
  UPDATE:
    goalflight_task.py block t-014 --on q-002
    goalflight_task.py lane t-014 held
    goalflight_task.py review t-014 --verdict clean --dispatch codex-review-123
    goalflight_task.py review t-014 --verdict findings --dispatch codex-review-123 --bug "Unfixed review finding" --bug-pattern bp-001
    goalflight_task.py harvest --json
    goalflight_task.py sync
  CLOSE:
    goalflight_task.py done t-014 --resolution worker-complete
    goalflight_task.py accept t-014
"""
    parser = argparse.ArgumentParser(
        description="Goal Flight task-backlog store/writer.",
        epilog=examples,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--project-root", help="Canonical project root. Defaults to git common-dir parent.")
    parser.add_argument("--by", help="Actor stamp override, e.g. user or watcher.")
    sub = parser.add_subparsers(dest="command", required=True)

    new = sub.add_parser(
        "new",
        help="Create a task, bug, or decision item.",
        epilog='example: goalflight_task.py new "Fix stale status" --kind bug --blocked-by q-002',
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    new.add_argument("--by", help=argparse.SUPPRESS)
    new.add_argument("title")
    new.add_argument("--kind", choices=["task", "bug", "decision"], default="task")
    new.add_argument("--id-family", choices=sorted(VALID_FAMILIES), help="Override id family; default follows --kind.")
    new.add_argument("--blocked-by", action="append", default=[])
    new.add_argument("--link", dest="links", action="append", default=[])
    new.add_argument("--tag", dest="tags", action="append", default=[])
    new.add_argument("--lane", help="Optional lane name. Reserved lanes: deferred, held.")
    new.add_argument("--acceptance")
    new.add_argument("--prompt")
    new.add_argument("--prompt-path")
    new.add_argument("--pattern")
    new.add_argument("--severity")
    new.add_argument("--source")
    new.add_argument("--json", action="store_true")
    new.set_defaults(func=_cmd_new)

    capture = sub.add_parser(
        "capture",
        help='CAPTURE: reflex-create a deferred task (bug if --severity). Common form: capture "<what>".',
        epilog=(
            "examples:\n"
            '  goalflight_task.py capture "Investigate flaky test"       # reflex: task, lane=deferred, source=cwd\n'
            '  goalflight_task.py capture "Race in retry path" --severity P2   # --severity -> a bug\n'
            '  goalflight_task.py capture "UI polish" --lane ui           # override the default lane'
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    capture.add_argument("--by", help=argparse.SUPPRESS)
    capture.add_argument("title")
    capture.add_argument(
        "--kind",
        choices=["task", "bug", "decision"],
        default=None,
        help="Default: task (or bug when --severity is given).",
    )
    capture.add_argument("--id-family", choices=sorted(VALID_FAMILIES), help="Override id family; default follows --kind.")
    capture.add_argument("--blocked-by", action="append", default=[])
    capture.add_argument("--link", dest="links", action="append", default=[])
    capture.add_argument("--tag", dest="tags", action="append", default=[])
    capture.add_argument("--lane", help="Default: deferred (the reserved backlog). Reserved lanes: deferred, held.")
    capture.add_argument("--acceptance")
    capture.add_argument("--prompt")
    capture.add_argument("--prompt-path")
    capture.add_argument("--pattern")
    capture.add_argument("--severity")
    capture.add_argument("--source", help="Default: the current working directory.")
    capture.add_argument("--json", action="store_true")
    capture.set_defaults(func=_cmd_capture)

    show = sub.add_parser(
        "show",
        help="Read one item by id.",
        epilog="examples:\n  goalflight_task.py show t-014\n  goalflight_task.py show t-014 --json\n  goalflight_task.py show t-014 --prompt",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    show.add_argument("--by", help=argparse.SUPPRESS)
    show.add_argument("item_id")
    show.add_argument("--prompt", action="store_true")
    show.add_argument("--json", action="store_true")
    show.set_defaults(func=_cmd_show)

    block = sub.add_parser(
        "block",
        help="Add blockers to an item.",
        epilog="example: goalflight_task.py block t-014 --on q-002",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    block.add_argument("--by", help=argparse.SUPPRESS)
    block.add_argument("item_id")
    block.add_argument("--on", action="append", required=True)
    block.set_defaults(func=_cmd_block)

    unblock = sub.add_parser(
        "unblock",
        help="Remove blockers from an item, or all blockers if --on is omitted.",
        epilog="example: goalflight_task.py unblock t-014 --on q-002",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    unblock.add_argument("--by", help=argparse.SUPPRESS)
    unblock.add_argument("item_id")
    unblock.add_argument("--on", action="append", default=[])
    unblock.set_defaults(func=_cmd_unblock)

    lane = sub.add_parser(
        "lane",
        help="UPDATE: set an item's lane.",
        epilog=(
            "examples:\n"
            "  goalflight_task.py lane t-014 held        # park pending re-auth/rethink (reserved)\n"
            "  goalflight_task.py lane t-014 deferred    # plan for later (reserved)\n"
            "  goalflight_task.py lane t-014 ui          # a free-text lane"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    lane.add_argument("--by", help=argparse.SUPPRESS)
    lane.add_argument("item_id")
    lane.add_argument("lane")
    lane.set_defaults(func=_cmd_lane)

    done = sub.add_parser(
        "done",
        help="Mark an item DONE/awaiting-review; accept moves it to DONE-REVIEWED.",
        epilog="example: goalflight_task.py done t-014 --resolution worker-complete",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    done.add_argument("--by", help=argparse.SUPPRESS)
    done.add_argument("item_id")
    done.add_argument("--resolution", default="done")
    done.add_argument("--force", action="store_true")
    done.set_defaults(func=_cmd_done)

    review = sub.add_parser(
        "review",
        help="Append a review breadcrumb to an item.",
        epilog="example: goalflight_task.py review t-014 --verdict clean --dispatch codex-review-123 --findings docs-private/reviews/t-014.md",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    review.add_argument("--by", help=argparse.SUPPRESS)
    review.add_argument("item_id")
    review.add_argument("--verdict", choices=["clean", "findings"], required=True)
    review.add_argument("--dispatch", required=True)
    review.add_argument("--findings")
    review.add_argument("--bug", dest="bugs", action="append", default=[], help="Confirmed, not-immediately-fixed review finding to capture as a bug item.")
    review.add_argument("--bug-pattern", help="Minted bug-pattern id/tag for --bug findings, e.g. bp-001.")
    review.add_argument("--bug-severity", default="medium")
    review.add_argument("--bug-tag", dest="bug_tags", action="append", default=[])
    review.add_argument("--json", action="store_true")
    review.set_defaults(func=_cmd_review)

    harvest = sub.add_parser(
        "harvest",
        help="Harvest open-work sources into draft task/bug/decision items and backfill history.md from RESUME-NOTES.",
        epilog="example: goalflight_task.py harvest --json",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    harvest.add_argument("--by", help=argparse.SUPPRESS)
    harvest.add_argument("--dry-run", action="store_true", help="Print discovered draft candidates without writing items or history.")
    harvest.add_argument("--no-history", action="store_true", help="Skip RESUME-NOTES -> history.md backfill.")
    harvest.add_argument("--json", action="store_true")
    harvest.set_defaults(func=_cmd_harvest)

    accept = sub.add_parser(
        "accept",
        help="Move DONE/awaiting-review to DONE-REVIEWED after a clean review.",
        epilog="example: goalflight_task.py accept t-014",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    accept.add_argument("--by", help=argparse.SUPPRESS)
    accept.add_argument("item_id")
    accept.set_defaults(func=_cmd_accept)

    list_cmd = sub.add_parser(
        "list",
        help="Query items with canned dashboard statuses and AND filters.",
        epilog="examples:\n  goalflight_task.py list outstanding\n  goalflight_task.py list awaiting-review --kind task\n  goalflight_task.py list delegated --since 1h --json\n  goalflight_task.py list --blocked-by q-002",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    list_cmd.add_argument("--by", help=argparse.SUPPRESS)
    list_cmd.add_argument("status", nargs="?", choices=sorted(CANNED_LIST_STATUSES))
    list_cmd.add_argument("--since", help="UTC lower bound: 1h, now-3600, epoch seconds, or ISO timestamp.")
    list_cmd.add_argument("--kind", choices=["task", "bug", "decision"])
    list_cmd.add_argument("--blocked-by", action="append", default=[])
    list_cmd.add_argument("--json", action="store_true")
    list_cmd.set_defaults(func=_cmd_list)

    status = sub.add_parser(
        "status",
        help="Print derived task status.",
        epilog="example: goalflight_task.py status --json",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    status.add_argument("--by", help=argparse.SUPPRESS)
    status.add_argument("--json", action="store_true")
    status.set_defaults(func=_cmd_status)

    sync = sub.add_parser(
        "sync",
        help="Write tasks-data.js and sync project-scoped dispatch breadcrumbs.",
        epilog="example: goalflight_task.py sync",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sync.add_argument("--by", help=argparse.SUPPRESS)
    sync.set_defaults(func=_cmd_sync)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    store = TaskStore(resolve_project_root(args.project_root))
    try:
        return args.func(store, args)
    except TaskError as exc:
        print(f"goalflight_task.py: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"goalflight_task.py: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
