#!/usr/bin/env python3
"""Goal Flight task-backlog store and mirror writer."""

from __future__ import annotations

import argparse
import contextlib
import datetime as dt
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
from typing import Any, Callable


ROOT = Path(__file__).resolve().parent
SCRIPTS = ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import goalflight_compat as fcntl  # noqa: E402

try:  # noqa: E402
    import goalflight_dispatch_states
    import goalflight_ledger
except Exception:  # pragma: no cover - import failures surface at runtime.
    goalflight_dispatch_states = None  # type: ignore[assignment]
    goalflight_ledger = None  # type: ignore[assignment]


CHECKER = ROOT / "scripts" / "check_tasks_mirror.js"
FAMILY_PREFIX_BY_KIND = {"task": "t", "bug": "b", "decision": "q"}
VALID_FAMILIES = {"t", "b", "q", "ADR"}


class TaskError(Exception):
    """User-facing task-store failure."""


class FileLock:
    def __init__(self, path: Path):
        self.path = path
        self._fh = None

    def __enter__(self) -> "FileLock":
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self._fh = self.path.open("a+", encoding="utf-8")
        fcntl.flock(self._fh, fcntl.LOCK_EX)
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        assert self._fh is not None
        fcntl.flock(self._fh, fcntl.LOCK_UN)
        self._fh.close()


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def _resolve_loose(path: Path) -> Path:
    return path.expanduser().resolve(strict=False)


def _strip_managed_worktree(path: Path) -> Path:
    resolved = _resolve_loose(path)
    parts = resolved.parts
    for index, part in enumerate(parts[:-2]):
        if part == ".claude" and parts[index + 1] == "worktrees":
            return _resolve_loose(Path(*parts[:index]))
    return resolved


def resolve_project_root(value: str | None = None) -> Path:
    explicit = value or os.environ.get("GOALFLIGHT_PROJECT_ROOT")
    if explicit:
        return _strip_managed_worktree(Path(explicit))

    cwd = Path.cwd()
    try:
        top = Path(
            subprocess.check_output(
                ["git", "rev-parse", "--show-toplevel"],
                cwd=str(cwd),
                text=True,
                stderr=subprocess.DEVNULL,
            ).strip()
        )
        common_raw = subprocess.check_output(
            ["git", "rev-parse", "--git-common-dir"],
            cwd=str(cwd),
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return _strip_managed_worktree(cwd)

    common = Path(common_raw)
    if not common.is_absolute():
        common = top / common
    if common.name == ".git":
        return _strip_managed_worktree(common.parent)
    return _strip_managed_worktree(top)


def _actor(args: argparse.Namespace) -> str:
    if getattr(args, "by", None):
        return args.by
    dispatch_id = os.environ.get("GOALFLIGHT_DISPATCH_ID")
    if dispatch_id:
        return f"worker:{dispatch_id}"
    return os.environ.get("GOALFLIGHT_TASK_ACTOR") or "controller"


def _audit(action: str, actor: str, **extra: Any) -> dict[str, Any]:
    entry: dict[str, Any] = {"at": utc_now(), "actor": actor, "action": action}
    entry.update({k: v for k, v in extra.items() if v not in (None, [], {})})
    return entry


def _append_audit(item: dict[str, Any], action: str, actor: str, **extra: Any) -> None:
    audit = item.setdefault("audit", [])
    if not isinstance(audit, list):
        raise TaskError(f"item {item.get('id', '<unknown>')}: audit must be an array")
    audit.append(_audit(action, actor, **extra))


def _canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _item_json_line(item: dict[str, Any]) -> str:
    return json.dumps(item, ensure_ascii=False, separators=(",", ":"))


def _items_jsonl(items: list[dict[str, Any]]) -> str:
    if not items:
        return ""
    return "".join(_item_json_line(item) + "\n" for item in items)


def _items_data_js(items: list[dict[str, Any]]) -> str:
    payload = json.dumps(items, ensure_ascii=False, indent=2)
    return (
        "// tasks-data.js - generated by goalflight_task.py; do not edit by hand.\n"
        "window.GF_ITEMS = "
        + payload
        + ";\n"
        "if (typeof module !== \"undefined\" && module.exports) { module.exports = window.GF_ITEMS; }\n"
    )


def _parse_jsonl(path: Path) -> tuple[list[dict[str, Any]], dict[str, int]]:
    if not path.exists():
        return [], {}
    items: list[dict[str, Any]] = []
    lines_by_id: dict[str, int] = {}
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not raw.strip():
            continue
        try:
            obj = json.loads(raw)
        except json.JSONDecodeError as exc:
            raise TaskError(f"{path}:{lineno}: invalid JSON: {exc.msg}") from exc
        if not isinstance(obj, dict):
            raise TaskError(f"{path}:{lineno}: expected a JSON object")
        item_id = obj.get("id")
        if not isinstance(item_id, str) or not item_id:
            raise TaskError(f"{path}:{lineno}: missing string id")
        if "status" in obj:
            raise TaskError(f"{path}:{lineno}: top-level status key is forbidden")
        if item_id in lines_by_id:
            raise TaskError(f"{path}:{lineno}: duplicate id {item_id} (first seen on line {lines_by_id[item_id]})")
        lines_by_id[item_id] = lineno
        items.append(obj)
    return items, lines_by_id


def _validate_items_for_write(items: list[dict[str, Any]], source: str = "tasks.jsonl") -> None:
    seen: dict[str, int] = {}
    for lineno, item in enumerate(items, start=1):
        if not isinstance(item, dict):
            raise TaskError(f"{source}: line {lineno}: expected a JSON object")
        item_id = item.get("id")
        if not isinstance(item_id, str) or not item_id:
            raise TaskError(f"{source}: line {lineno}: missing string id")
        if "status" in item:
            raise TaskError(f"{source}: line {lineno}: item {item_id} carries forbidden top-level status key")
        if item_id in seen:
            raise TaskError(f"{source}: line {lineno}: duplicate id {item_id} (first seen on line {seen[item_id]})")
        seen[item_id] = lineno
        item.setdefault("blocked_by", [])
        item.setdefault("links", [])
        item.setdefault("done", False)
        if not isinstance(item["blocked_by"], list):
            raise TaskError(f"{source}: line {lineno}: item {item_id} blocked_by must be an array")
        if not isinstance(item["links"], list):
            raise TaskError(f"{source}: line {lineno}: item {item_id} links must be an array")


def _run_checker(directory: Path) -> None:
    node = shutil.which("node")
    if not node:
        raise TaskError("scripts/check_tasks_mirror.js: node not found; refusing to write without strict mirror validation")
    if not CHECKER.is_file():
        raise TaskError(f"{CHECKER}: missing strict mirror checker")
    proc = subprocess.run(
        [node, str(CHECKER), str(directory)],
        cwd=str(ROOT),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=30,
        check=False,
    )
    if proc.returncode != 0:
        msg = (proc.stderr or proc.stdout).strip() or f"checker exited {proc.returncode}"
        raise TaskError(msg)


def _parse_time(value: Any) -> dt.datetime:
    if not isinstance(value, str) or not value:
        return dt.datetime.min.replace(tzinfo=dt.timezone.utc)
    try:
        parsed = dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return dt.datetime.min.replace(tzinfo=dt.timezone.utc)
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt.timezone.utc)
    return parsed.astimezone(dt.timezone.utc)


def _record_sort_time(record: dict[str, Any]) -> dt.datetime:
    for key in ("updated_at", "ended_at", "started_at"):
        parsed = _parse_time(record.get(key))
        if parsed != dt.datetime.min.replace(tzinfo=dt.timezone.utc):
            return parsed
    return dt.datetime.min.replace(tzinfo=dt.timezone.utc)


def _record_terminal_state(record: dict[str, Any]) -> str:
    terminal = record.get("terminal_state")
    if isinstance(terminal, str) and terminal:
        return terminal
    if goalflight_ledger is not None:
        return str(goalflight_ledger.terminal_state_for(record.get("state"), record.get("reason") or record.get("error")))
    return "unknown"


def _dispatch_status_from_record(record: dict[str, Any], *, live: bool) -> str | None:
    terminal = _record_terminal_state(record)
    state = record.get("state")
    normalized = None
    if goalflight_dispatch_states is not None:
        normalized = goalflight_dispatch_states.normalize_dispatch_state(state)

    if terminal == "complete" or normalized == "complete":
        return "worker-finished"
    if terminal not in {"", "unknown", None}:
        return "worker-failed"
    if isinstance(state, str) and state.startswith("blocked"):
        return "worker-failed"

    if live:
        if normalized in {"waiting", "starting", "running", "running_quiet"} or state in {
            "queued",
            "waiting_capacity",
            "handshaking",
        }:
            if goalflight_ledger is not None:
                classification = goalflight_ledger.classify(record)
                if classification.startswith("stale_") or classification in {"unknown_no_pid", "watcher_stopped"}:
                    return "worker-failed"
            return "working"
        return "worker-failed"

    return None


def _breadcrumb_from_record(record: dict[str, Any]) -> dict[str, Any]:
    crumb: dict[str, Any] = {
        "dispatch_id": record.get("dispatch_id"),
        "agent": record.get("agent"),
        "log": record.get("stdout_path") or record.get("log"),
        "stdout_path": record.get("stdout_path"),
        "stderr_path": record.get("stderr_path"),
        "status_path": record.get("status_path"),
        "started_at": record.get("started_at"),
        "ended_at": record.get("ended_at"),
        "state": record.get("state"),
        "terminal_state": _record_terminal_state(record),
        "marker": record.get("marker"),
        "worker_pid": record.get("worker_pid"),
        "hostname": record.get("hostname"),
    }
    return {k: v for k, v in crumb.items() if v not in (None, "", [], {})}


def _last_terminal_breadcrumb(item: dict[str, Any]) -> dict[str, Any] | None:
    dispatches = item.get("dispatches")
    if not isinstance(dispatches, list):
        return None
    terminal = []
    for crumb in dispatches:
        if not isinstance(crumb, dict):
            continue
        if _dispatch_status_from_record(crumb, live=False):
            terminal.append(crumb)
    if not terminal:
        return None
    return sorted(terminal, key=_record_sort_time)[-1]


class TaskStore:
    def __init__(self, project_root: Path):
        self.project_root = _strip_managed_worktree(project_root)
        self.docs_dir = self.project_root / "docs-private"
        self.tasks_path = self.docs_dir / "tasks.jsonl"
        self.data_js_path = self.docs_dir / "tasks-data.js"
        self.store_lock_path = self.docs_dir / "tasks.lock"
        self.seq_path = self.docs_dir / ".task-seq"
        self.seq_lock_path = self.docs_dir / ".task-seq.lock"
        self.log_dir = self.docs_dir / "log"

    @contextlib.contextmanager
    def store_lock(self):
        self.docs_dir.mkdir(parents=True, exist_ok=True)
        with FileLock(self.store_lock_path):
            yield

    def load_items(self) -> list[dict[str, Any]]:
        items, _ = _parse_jsonl(self.tasks_path)
        return items

    def items_by_id(self) -> dict[str, dict[str, Any]]:
        return {item["id"]: item for item in self.load_items()}

    def reserve_id(self, family: str) -> str:
        if family not in VALID_FAMILIES:
            raise TaskError(f"unknown id family {family!r}; expected one of {', '.join(sorted(VALID_FAMILIES))}")
        self.docs_dir.mkdir(parents=True, exist_ok=True)
        with FileLock(self.seq_lock_path):
            seq = self._read_seq()
            current = int(seq.get(family, 0))
            next_value = current + 1
            seq[family] = next_value
            tmp = self.seq_path.with_suffix(".tmp")
            tmp.write_text(json.dumps(seq, indent=2, sort_keys=True) + "\n", encoding="utf-8")
            tmp.replace(self.seq_path)
        return f"ADR-{next_value:03d}" if family == "ADR" else f"{family}-{next_value:03d}"

    def _read_seq(self) -> dict[str, int]:
        if not self.seq_path.exists():
            return {}
        text = self.seq_path.read_text(encoding="utf-8").strip()
        if not text:
            return {}
        if text.isdigit():
            return {"t": int(text)}
        try:
            raw = json.loads(text)
        except json.JSONDecodeError as exc:
            raise TaskError(f"{self.seq_path}:1: invalid JSON: {exc.msg}") from exc
        if not isinstance(raw, dict):
            raise TaskError(f"{self.seq_path}:1: expected a JSON object")
        out: dict[str, int] = {}
        for key, value in raw.items():
            if key not in VALID_FAMILIES:
                raise TaskError(f"{self.seq_path}:1: unknown id family {key!r}")
            if not isinstance(value, int) or value < 0:
                raise TaskError(f"{self.seq_path}:1: family {key!r} must be a non-negative integer")
            out[key] = value
        return out

    def mutate_items(self, update: Callable[[list[dict[str, Any]]], Any], *, allow_invalid_live_mirror: bool = False) -> Any:
        with self.store_lock():
            self._snapshot_last_good(require_valid=not allow_invalid_live_mirror)
            items = self.load_items()
            result = update(items)
            self.save_items_atomic(items)
            return result

    def save_items_atomic(self, items: list[dict[str, Any]]) -> None:
        self.docs_dir.mkdir(parents=True, exist_ok=True)
        _validate_items_for_write(items)
        staging = Path(tempfile.mkdtemp(prefix=".tasks-stage-", dir=str(self.docs_dir)))
        try:
            (staging / "tasks.jsonl").write_text(_items_jsonl(items), encoding="utf-8")
            (staging / "tasks-data.js").write_text(_items_data_js(items), encoding="utf-8")
            _run_checker(staging)
            old_tasks = self.tasks_path.read_bytes() if self.tasks_path.exists() else None
            old_data = self.data_js_path.read_bytes() if self.data_js_path.exists() else None
            try:
                (staging / "tasks.jsonl").replace(self.tasks_path)
                (staging / "tasks-data.js").replace(self.data_js_path)
            except OSError:
                self._restore_bytes(self.tasks_path, old_tasks)
                self._restore_bytes(self.data_js_path, old_data)
                raise
        finally:
            shutil.rmtree(staging, ignore_errors=True)

    @staticmethod
    def _restore_bytes(path: Path, data: bytes | None) -> None:
        if data is None:
            with contextlib.suppress(FileNotFoundError):
                path.unlink()
            return
        tmp = path.with_suffix(path.suffix + ".restore")
        tmp.write_bytes(data)
        tmp.replace(path)

    def _snapshot_last_good(self, *, require_valid: bool = True) -> None:
        if not self.tasks_path.exists() and not self.data_js_path.exists():
            return
        if not self.tasks_path.exists() or not self.data_js_path.exists():
            if not require_valid and self.tasks_path.exists():
                return
            raise TaskError(f"{self.docs_dir}: missing tasks.jsonl or tasks-data.js; refusing mutation without a valid last-known-good pair")
        try:
            _run_checker(self.docs_dir)
        except TaskError:
            if require_valid:
                raise
            return
        self.log_dir.mkdir(parents=True, exist_ok=True)
        stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
        shutil.copy2(self.tasks_path, self.log_dir / f"tasks-{stamp}.jsonl")
        shutil.copy2(self.data_js_path, self.log_dir / f"tasks-data-{stamp}.js")
        self._prune_backups()

    def _prune_backups(self, keep: int = 20) -> None:
        for pattern in ("tasks-*.jsonl", "tasks-data-*.js"):
            backups = sorted(self.log_dir.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
            for path in backups[keep:]:
                with contextlib.suppress(OSError):
                    path.unlink()

    def project_ledger_records(self) -> list[dict[str, Any]]:
        if goalflight_ledger is None:
            return []
        target = _strip_managed_worktree(self.project_root)
        records = []
        for record in goalflight_ledger.read_records():
            task_id = record.get("task_id")
            if not isinstance(task_id, str) or not task_id:
                continue
            raw_root = record.get("project_root")
            if not isinstance(raw_root, str) or not raw_root:
                continue
            if _strip_managed_worktree(Path(raw_root)) == target:
                records.append(record)
        return records

    def sync_dispatch_breadcrumbs(self, items: list[dict[str, Any]], actor: str) -> int:
        by_id = {item["id"]: item for item in items}
        changed = 0
        for record in self.project_ledger_records():
            task_id = record.get("task_id")
            dispatch_id = record.get("dispatch_id")
            if not isinstance(task_id, str) or not isinstance(dispatch_id, str):
                continue
            item = by_id.get(task_id)
            if item is None:
                continue
            crumb = _breadcrumb_from_record(record)
            dispatches = item.setdefault("dispatches", [])
            if not isinstance(dispatches, list):
                raise TaskError(f"item {task_id}: dispatches must be an array")
            existing_index = next(
                (index for index, entry in enumerate(dispatches) if isinstance(entry, dict) and entry.get("dispatch_id") == dispatch_id),
                None,
            )
            if existing_index is None:
                dispatches.append(crumb)
                changed += 1
                _append_audit(item, "dispatch-sync", actor, dispatch_id=dispatch_id, state=crumb.get("state"))
            elif _canonical_json(dispatches[existing_index]) != _canonical_json(crumb):
                dispatches[existing_index] = crumb
                changed += 1
                _append_audit(item, "dispatch-sync", actor, dispatch_id=dispatch_id, state=crumb.get("state"))
        return changed

    def derived_rows(self) -> list[dict[str, Any]]:
        items = self.load_items()
        records_by_task: dict[str, list[dict[str, Any]]] = {}
        for record in self.project_ledger_records():
            records_by_task.setdefault(str(record["task_id"]), []).append(record)

        rows = []
        for item in items:
            item_id = item["id"]
            row = dict(item)
            row["derived_status"] = self._derive_status(item, records_by_task.get(item_id, []))
            rows.append(row)
        return rows

    def _derive_status(self, item: dict[str, Any], live_records: list[dict[str, Any]]) -> str:
        if item.get("done") is True:
            return "done"
        if live_records:
            latest = sorted(live_records, key=_record_sort_time)[-1]
            status = _dispatch_status_from_record(latest, live=True)
            if status:
                return status
        crumb = _last_terminal_breadcrumb(item)
        if crumb:
            status = _dispatch_status_from_record(crumb, live=False)
            if status:
                return status
        if item.get("blocked_by"):
            return "blocked"
        return "pending"


def _split_csv(values: list[str] | None) -> list[str]:
    out: list[str] = []
    for value in values or []:
        for part in value.split(","):
            part = part.strip()
            if part:
                out.append(part)
    return out


def _cmd_new(store: TaskStore, args: argparse.Namespace) -> int:
    family = args.id_family or FAMILY_PREFIX_BY_KIND[args.kind]
    item_id = store.reserve_id(family)
    actor = _actor(args)

    def update(items: list[dict[str, Any]]) -> str:
        if any(item.get("id") == item_id for item in items):
            raise TaskError(f"{store.tasks_path}: id {item_id} already exists; .task-seq is stale")
        item: dict[str, Any] = {
            "id": item_id,
            "kind": args.kind,
            "title": args.title,
            "blocked_by": _split_csv(args.blocked_by),
            "links": _split_csv(args.links),
            "done": False,
            "tags": _split_csv(args.tags),
            "created_at": utc_now(),
            "created_by": actor,
            "audit": [_audit("new", actor)],
        }
        for key in ("acceptance", "prompt", "prompt_path", "pattern", "severity", "source"):
            value = getattr(args, key, None)
            if value not in (None, "", [], {}):
                item[key] = value
        items.append(item)
        return item_id

    created = store.mutate_items(update)
    if args.json:
        print(json.dumps({"id": created}, sort_keys=True))
    else:
        print(created)
    return 0


def _cmd_show(store: TaskStore, args: argparse.Namespace) -> int:
    by_id = store.items_by_id()
    item = by_id.get(args.item_id)
    if item is None:
        raise TaskError(f"{store.tasks_path}: item not found: {args.item_id}")
    if args.prompt:
        prompt = item.get("prompt")
        if isinstance(prompt, str):
            print(prompt)
            return 0
        prompt_path = item.get("prompt_path")
        if isinstance(prompt_path, str) and prompt_path:
            path = Path(prompt_path)
            if not path.is_absolute():
                path = store.project_root / path
            print(path.read_text(encoding="utf-8"), end="")
            return 0
        raise TaskError(f"{args.item_id}: no prompt or prompt_path")
    print(json.dumps(item, indent=2, ensure_ascii=False, sort_keys=True))
    return 0


def _cmd_block(store: TaskStore, args: argparse.Namespace) -> int:
    blockers = _split_csv(args.on)
    if not blockers:
        raise TaskError("block: --on requires at least one blocker id")
    actor = _actor(args)

    def update(items: list[dict[str, Any]]) -> None:
        by_id = {item["id"]: item for item in items}
        item = by_id.get(args.item_id)
        if item is None:
            raise TaskError(f"{store.tasks_path}: item not found: {args.item_id}")
        blocked_by = item.setdefault("blocked_by", [])
        if not isinstance(blocked_by, list):
            raise TaskError(f"item {args.item_id}: blocked_by must be an array")
        for blocker in blockers:
            if blocker not in blocked_by:
                blocked_by.append(blocker)
        _append_audit(item, "block", actor, on=blockers)

    store.mutate_items(update)
    print(args.item_id)
    return 0


def _cmd_unblock(store: TaskStore, args: argparse.Namespace) -> int:
    actor = _actor(args)
    remove = set(_split_csv(args.on))

    def update(items: list[dict[str, Any]]) -> None:
        by_id = {item["id"]: item for item in items}
        item = by_id.get(args.item_id)
        if item is None:
            raise TaskError(f"{store.tasks_path}: item not found: {args.item_id}")
        blocked_by = item.setdefault("blocked_by", [])
        if not isinstance(blocked_by, list):
            raise TaskError(f"item {args.item_id}: blocked_by must be an array")
        item["blocked_by"] = [value for value in blocked_by if remove and value not in remove] if remove else []
        _append_audit(item, "unblock", actor, on=sorted(remove) if remove else None)

    store.mutate_items(update)
    print(args.item_id)
    return 0


def _cmd_done(store: TaskStore, args: argparse.Namespace) -> int:
    actor = _actor(args)

    def update(items: list[dict[str, Any]]) -> None:
        by_id = {item["id"]: item for item in items}
        item = by_id.get(args.item_id)
        if item is None:
            raise TaskError(f"{store.tasks_path}: item not found: {args.item_id}")
        if item.get("done") is True:
            raise TaskError(f"{args.item_id}: already done")
        if item.get("blocked_by") and not args.force:
            raise TaskError(f"{args.item_id}: blocked_by is non-empty; use --force to close anyway")
        item["done"] = True
        item["closed_at"] = utc_now()
        item["closed_by"] = actor
        item["resolution"] = args.resolution
        _append_audit(item, "done", actor, resolution=args.resolution)

    store.mutate_items(update)
    print(args.item_id)
    return 0


def _cmd_status(store: TaskStore, args: argparse.Namespace) -> int:
    rows = store.derived_rows()
    if args.json:
        payload = {"project_root": str(store.project_root), "items": rows}
        print(json.dumps(payload, ensure_ascii=False, sort_keys=True))
        return 0
    for row in rows:
        print(f"{row['id']} {row['derived_status']} {row.get('title', '')}")
    return 0


def _cmd_sync(store: TaskStore, args: argparse.Namespace) -> int:
    actor = _actor(args)

    def update(items: list[dict[str, Any]]) -> int:
        return store.sync_dispatch_breadcrumbs(items, actor)

    changed = store.mutate_items(update, allow_invalid_live_mirror=True)
    print(f"OK: synced tasks-data.js ({changed} dispatch breadcrumb updates)")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Goal Flight task-backlog store/writer.")
    parser.add_argument("--project-root", help="Canonical project root. Defaults to git common-dir parent.")
    parser.add_argument("--by", help="Actor stamp override, e.g. user or watcher.")
    sub = parser.add_subparsers(dest="command", required=True)

    new = sub.add_parser("new", help="Create a task, bug, or decision item.")
    new.add_argument("--by", help=argparse.SUPPRESS)
    new.add_argument("title")
    new.add_argument("--kind", choices=["task", "bug", "decision"], default="task")
    new.add_argument("--id-family", choices=sorted(VALID_FAMILIES), help="Override id family; default follows --kind.")
    new.add_argument("--blocked-by", action="append", default=[])
    new.add_argument("--link", dest="links", action="append", default=[])
    new.add_argument("--tag", dest="tags", action="append", default=[])
    new.add_argument("--acceptance")
    new.add_argument("--prompt")
    new.add_argument("--prompt-path")
    new.add_argument("--pattern")
    new.add_argument("--severity")
    new.add_argument("--source")
    new.add_argument("--json", action="store_true")
    new.set_defaults(func=_cmd_new)

    show = sub.add_parser("show", help="Read one item by id.")
    show.add_argument("--by", help=argparse.SUPPRESS)
    show.add_argument("item_id")
    show.add_argument("--prompt", action="store_true")
    show.set_defaults(func=_cmd_show)

    block = sub.add_parser("block", help="Add blockers to an item.")
    block.add_argument("--by", help=argparse.SUPPRESS)
    block.add_argument("item_id")
    block.add_argument("--on", action="append", required=True)
    block.set_defaults(func=_cmd_block)

    unblock = sub.add_parser("unblock", help="Remove blockers from an item, or all blockers if --on is omitted.")
    unblock.add_argument("--by", help=argparse.SUPPRESS)
    unblock.add_argument("item_id")
    unblock.add_argument("--on", action="append", default=[])
    unblock.set_defaults(func=_cmd_unblock)

    done = sub.add_parser("done", help="Mark an item done.")
    done.add_argument("--by", help=argparse.SUPPRESS)
    done.add_argument("item_id")
    done.add_argument("--resolution", default="done")
    done.add_argument("--force", action="store_true")
    done.set_defaults(func=_cmd_done)

    status = sub.add_parser("status", help="Print derived task status.")
    status.add_argument("--by", help=argparse.SUPPRESS)
    status.add_argument("--json", action="store_true")
    status.set_defaults(func=_cmd_status)

    sync = sub.add_parser("sync", help="Write tasks-data.js and sync project-scoped dispatch breadcrumbs.")
    sync.add_argument("--by", help=argparse.SUPPRESS)
    sync.set_defaults(func=_cmd_sync)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    store = TaskStore(resolve_project_root(args.project_root))
    try:
        return args.func(store, args)
    except TaskError as exc:
        print(f"goalflight_task.py: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"goalflight_task.py: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
