// tasks-data.js - generated by goalflight_task.py; do not edit by hand.
window.GF_ITEMS = [
  {
    "id": "t-001",
    "kind": "task",
    "title": "Fixture open task - replace with real project work.",
    "blocked_by": [],
    "links": [],
    "done": false,
    "derived_status": "pending",
    "acceptance": "used by mirror drift tests."
  },
  {
    "id": "t-002",
    "kind": "task",
    "title": "Fixture done task - mirrors a completed chunk.",
    "blocked_by": [
      "t-001"
    ],
    "links": [
      "NORTH-STAR.md"
    ],
    "done": true,
    "done_reviewed": true,
    "derived_status": "done-reviewed",
    "acceptance": "shown in the Done section of fixture views."
  }
];
if (typeof module !== "undefined" && module.exports) { module.exports = window.GF_ITEMS; }
