#!/usr/bin/env python3
"""Scheduled fleet-console producer lock, budget, and publication tests."""

from __future__ import annotations

import contextlib
import io
import json
import os
import subprocess
import sys
import tempfile
import threading
import time
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))

import goalflight_fleet_console as console
import goalflight_fleet_console_producer as producer


def _script_payload(path: Path, global_name: str) -> dict:
    text = path.read_text(encoding="utf-8")
    prefix = f"window.{global_name} = "
    assert text.startswith("// generated by goalflight_status.py")
    assignment = text[text.index(prefix) + len(prefix) :]
    assert assignment.endswith(";\n")
    return json.loads(assignment[:-2])


def _write_python(path: Path, body: str) -> None:
    path.write_text("#!/usr/bin/env python3\n" + body, encoding="utf-8")


def test_second_tick_refuses_held_plane_lock_visibly() -> None:
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        ready = root / "holder-ready"
        slow = root / "slow-holder.py"
        _write_python(
            slow,
            "import pathlib, time\n"
            f"pathlib.Path({str(ready)!r}).write_text('ready', encoding='utf-8')\n"
            "time.sleep(0.5)\n",
        )
        holder_code = (
            "import pathlib, sys; "
            f"sys.path.insert(0, {str(ROOT / 'scripts')!r}); "
            "import goalflight_fleet_console_producer as producer; "
            "raise SystemExit(producer.run_tick("
            f"'fleet', output=pathlib.Path({str(root / 'holder.js')!r}), "
            f"lock_dir=pathlib.Path({str(root / 'locks')!r}), "
            f"producer_script=pathlib.Path({str(slow)!r}), budget_s=1.0))"
        )
        holder = subprocess.Popen([sys.executable, "-c", holder_code])
        deadline = time.monotonic() + 2
        while not ready.exists() and time.monotonic() < deadline:
            time.sleep(0.01)
        assert ready.exists(), "first tick never reached its locked producer"
        err = io.StringIO()
        try:
            with contextlib.redirect_stderr(err):
                code = producer.run_tick(
                    "fleet",
                    output=root / "never-written.js",
                    lock_dir=root / "locks",
                    producer_script=root / "must-not-run.py",
                    budget_s=0.1,
                )
        finally:
            holder.wait(timeout=2)

        assert holder.returncode == 0
        assert code == producer.EXIT_OVERLAP
        assert "SKIPPED: overlap lock held" in err.getvalue()
        assert "fleet" in err.getvalue()
        assert not (root / "never-written.js").exists()


def test_plane_locks_are_independent() -> None:
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        quick = root / "quick.py"
        _write_python(quick, "raise SystemExit(0)\n")

        fleet_holder = producer.PlaneLock(root / "locks", "fleet")
        assert fleet_holder.acquire()
        try:
            assert producer.run_tick(
                "attention",
                output=root / "attention.js",
                lock_dir=root / "locks",
                producer_script=quick,
                budget_s=0.5,
            ) == 0
        finally:
            fleet_holder.release()

        attention_holder = producer.PlaneLock(root / "locks", "attention")
        assert attention_holder.acquire()
        try:
            assert producer.run_tick(
                "fleet",
                output=root / "fleet.js",
                lock_dir=root / "locks",
                producer_script=quick,
                budget_s=0.5,
            ) == 0
        finally:
            attention_holder.release()


def test_slow_catch_up_does_not_hold_the_fast_plane_lock() -> None:
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        lock_was_free: list[bool] = []

        def catch_up(*_args: object, **_kwargs: object) -> dict[str, int]:
            contender = producer.PlaneLock(root / "locks", "fleet")
            acquired = contender.acquire()
            lock_was_free.append(acquired)
            contender.release()
            return {"prompts": 0, "history": 0}

        with (
            mock.patch.object(producer, "_run_with_budget", return_value=0),
            mock.patch.object(producer.history, "catch_up_if_due", side_effect=catch_up),
        ):
            code = producer.run_tick(
                "fleet",
                output=root / "fleet-data.js",
                lock_dir=root / "locks",
                budget_s=0.5,
            )

    assert code == 0
    assert lock_was_free == [True]


def test_budget_timeout_publishes_degraded_sample_and_exit_one() -> None:
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        slow = root / "slow.py"
        child_pid = root / "slow-child.pid"
        _write_python(
            slow,
            "import pathlib, subprocess, sys, time\n"
            "child = subprocess.Popen([sys.executable, '-c', 'import time; time.sleep(2)'])\n"
            f"pathlib.Path({str(child_pid)!r}).write_text(str(child.pid), encoding='utf-8')\n"
            "time.sleep(2)\n",
        )
        output = root / "fleet-data.js"
        err = io.StringIO()

        began = time.monotonic()
        with contextlib.redirect_stderr(err):
            code = producer.run_tick(
                "fleet",
                output=output,
                lock_dir=root / "locks",
                producer_script=slow,
                budget_s=0.5,
            )
        elapsed = time.monotonic() - began

        assert code == 1
        assert elapsed < 1.5, f"budget failed to stop slow child: {elapsed:.3f}s"
        payload = _script_payload(output, "GF_FLEET")
        assert payload["last_success_at"] is None
        assert str(payload["last_error"]).startswith("budget:TimeoutExpired")
        assert "fleet-console-fleet-launchd.log" in str(payload["last_error"])
        assert "install-fleet-console.sh --status --plane fleet" in str(payload["last_error"])
        assert payload["registry_deep_sampled"] == 0
        assert payload["registry_total"] is None
        assert payload["projects"] == []
        assert "budget exhausted" in err.getvalue()
        assert "DEGRADED" in err.getvalue()

        assert child_pid.exists(), "slow sampler never started its descendant"
        descendant = int(child_pid.read_text(encoding="utf-8"))
        deadline = time.monotonic() + 0.5
        while time.monotonic() < deadline:
            try:
                os.kill(descendant, 0)
            except ProcessLookupError:
                break
            time.sleep(0.01)
        else:
            raise AssertionError(f"budget left descendant process {descendant} alive")

        # The timed-out path must release its lock after publishing the sample.
        after = producer.PlaneLock(root / "locks", "fleet")
        assert after.acquire()
        after.release()


def _large_attention_payload(generation_id: str, marker: str) -> dict:
    payload = console.build_degraded_plane(
        "attention",
        error="synthetic:RuntimeError",
        generation_id=generation_id,
    )
    payload["last_success_at"] = payload["sample_finished_at"]
    payload["last_error"] = None
    payload["items"] = [
        {
            "dispatch_id": f"{marker}-{index}",
            "seq": index,
            "kind": "advisory",
            "action": "review",
            "observed_at": "2026-08-02T00:00:00+00:00",
            "headline": marker * 96,
        }
        for index in range(3500)
    ]
    console.validate_projection(payload, "attention")
    return payload


def test_atomic_publisher_never_exposes_partial_script_to_reader() -> None:
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        payload_a = _large_attention_payload("generation-a", "A")
        payload_b = _large_attention_payload("generation-b", "B")
        reference_a = root / "reference-a.js"
        reference_b = root / "reference-b.js"
        target = root / "attention-data.js"
        console.publish_plane(reference_a, payload_a, "attention")
        console.publish_plane(reference_b, payload_b, "attention")
        complete_scripts = {
            reference_a.read_text(encoding="utf-8"),
            reference_b.read_text(encoding="utf-8"),
        }
        target.write_text(reference_a.read_text(encoding="utf-8"), encoding="utf-8")

        done = threading.Event()
        ready = threading.Event()
        begin = threading.Event()
        failures: list[str] = []

        def writer() -> None:
            try:
                ready.set()
                begin.wait(timeout=5)
                for index in range(12):
                    payload = payload_b if index % 2 else payload_a
                    console.publish_plane(target, payload, "attention")
            except BaseException as exc:  # surfaced in the reader thread below
                failures.append(f"writer failed: {exc}")
            finally:
                done.set()

        thread = threading.Thread(target=writer, daemon=True)
        thread.start()
        assert ready.wait(timeout=5)
        begin.set()
        observations = 0
        while not done.is_set() or thread.is_alive():
            observed = target.read_text(encoding="utf-8")
            observations += 1
            if observed not in complete_scripts:
                failures.append(f"reader observed partial script ({len(observed)} bytes)")
                break
        thread.join(timeout=5)

        assert not thread.is_alive()
        assert observations > 0
        assert failures == []
