#!/usr/bin/env python3
"""Event-driven immutable history and prompt mirrors for the fleet console.

The short-poll producers must not carry permanent terminal history or prompt
text.  Ledger transitions call this module best-effort, while the fleet
producer performs an hourly idempotent catch-up for events missed during a
crash or upgrade.
"""

from __future__ import annotations

import contextlib
import datetime as dt
import errno
import hashlib
import json
import os
from pathlib import Path
import re
import tempfile
import time
from typing import Callable, Iterable

import goalflight_compat as fcntl
import goalflight_dispatch_states


HISTORY_SCHEMA = "goalflight.fleet-console.history.v1"
HISTORY_GLOBAL = "GF_HISTORY"
CATCH_UP_INTERVAL_S = 60 * 60
_SCRIPT_PREFIX = (
    "// generated by goalflight_fleet_console_history.py; do not edit by hand.\n"
    f"window.{HISTORY_GLOBAL} = "
)
_CONTROL = re.compile(r"[\x00-\x1f\x7f]+")
_ABSOLUTE_PATH = re.compile(
    r"(^|[\s(\[{'\"])/(?!/)[^\s<>\"']+|(^|[\s(\[{'\"])[A-Za-z]:\\[^\s<>\"']+"
)


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def _display(value: object, *, limit: int = 128) -> str | None:
    if value is None:
        return None
    if isinstance(value, (dict, list, tuple, set)):
        return None
    text = _CONTROL.sub(" ", str(value)).strip()
    text = _ABSOLUTE_PATH.sub(
        lambda match: f"{match.group(1) or match.group(2) or ''}[path]",
        text,
    )
    return text[:limit] or None


def _timestamp(value: object) -> str | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        parsed = dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt.timezone.utc)
    return parsed.astimezone(dt.timezone.utc).isoformat(timespec="seconds")


def project_id(project_root: object) -> str:
    root = str(Path(str(project_root or "unknown")).expanduser().resolve(strict=False))
    name = Path(root).name or "project"
    safe_name = re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip("-") or "project"
    digest = hashlib.sha256(root.encode("utf-8")).hexdigest()[:10]
    return f"{safe_name}-{digest}"


def prompt_filename(dispatch_id: object) -> str | None:
    if not isinstance(dispatch_id, str):
        return None
    value = _CONTROL.sub(" ", dispatch_id).strip()[:512]
    if not value:
        return None
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:32] + ".txt"


def configured_output_dir() -> Path | None:
    supplied = os.environ.get("GOALFLIGHT_FLEET_CONSOLE_OUTPUT_DIR")
    if supplied:
        return Path(supplied).expanduser().resolve()
    config_path = Path(
        os.environ.get(
            "GOALFLIGHT_FLEET_CONSOLE_CONFIG",
            str(Path.home() / ".goal-flight" / "fleet-console-output-dir"),
        )
    ).expanduser()
    try:
        configured = config_path.read_text(encoding="utf-8").strip()
    except OSError:
        configured = ""
    if configured:
        return Path(configured).expanduser().resolve()
    # History hooks are opt-in through the installer-owned config. Without it,
    # an installed skill must not keep writing prompt/history files after the
    # console has been uninstalled. The producer passes its output directory
    # explicitly for catch-up, so a missed event remains recoverable.
    return None


def _resolved_output_dir(output_dir: Path | None) -> Path | None:
    return output_dir.expanduser().resolve() if output_dir is not None else configured_output_dir()


def _is_terminal(record: dict) -> bool:
    return any(
        goalflight_dispatch_states.is_terminal_state(record.get(key))
        for key in ("terminal_state", "state", "classification")
    )


def _controller_fields(record: dict) -> dict[str, object]:
    label = _display(record.get("controller_label"), limit=64)
    session = _display(record.get("controller_session_id"), limit=256)
    raw_pid = record.get("controller_pid")
    pid = raw_pid if isinstance(raw_pid, int) and not isinstance(raw_pid, bool) and raw_pid > 0 else None
    if label:
        display, state = label, "label"
    elif session:
        digest = hashlib.sha256(session.encode("utf-8")).hexdigest()[:16]
        display, state = f"session · {digest}", "session"
    elif pid is not None:
        display, state = "owned · identity unknown", "owned_unknown"
    else:
        display, state = "unowned", "unowned"
    return {
        "controller_session_digest": (
            hashlib.sha256(session.encode("utf-8")).hexdigest()[:16] if session else None
        ),
        "controller_pid": pid,
        "controller_label": label,
        "controller_display": display,
        "controller_state": state,
        "controller_liveness_state": "UNKNOWN",
    }


def history_worker_row(record: dict) -> dict[str, object]:
    terminal = _display(record.get("terminal_state") or record.get("state"), limit=64)
    normalized = goalflight_dispatch_states.normalize_dispatch_state(terminal) or "terminal"
    sandbox = record.get("os_sandbox") if isinstance(record.get("os_sandbox"), dict) else {}
    task_ids = record.get("task_ids") if isinstance(record.get("task_ids"), list) else []
    return {
        "dispatch_id": _display(record.get("dispatch_id"), limit=128),
        "node_id": "local",
        "agent": _display(record.get("agent"), limit=64),
        "engine": _display(record.get("engine"), limit=64),
        "shape": _display(record.get("shape"), limit=64),
        "transport": _display(record.get("transport"), limit=64),
        "os_sandbox": _display(record.get("os_sandbox"), limit=32),
        "os_sandbox_requested": _display(sandbox.get("requested_profile"), limit=32),
        "os_sandbox_supported": _display(sandbox.get("supported_profile"), limit=32),
        "os_sandbox_enforced": _display(sandbox.get("enforced_profile"), limit=32),
        "state": _display(record.get("state"), limit=64),
        "classification": _display(record.get("classification"), limit=64),
        "terminal_state": terminal,
        "liveness_state": _display(record.get("liveness_state"), limit=64),
        "worker_alive": False,
        "started_at": _timestamp(record.get("started_at")),
        "ended_at": _timestamp(record.get("ended_at") or record.get("updated_at")),
        "display_state": normalized,
        "is_terminal": True,
        "classification_conflict": False,
        "authority_detail": None,
        "authority_resolution": None,
        **_controller_fields(record),
        "age_filter_match": False,
        "age_filter_reason": "terminal",
        "observed_live": False,
        "observed_live_source": "terminal_history",
        "task_ids": [
            item
            for item in (_display(task_id, limit=64) for task_id in task_ids)
            if item is not None
        ],
        "prompt_file": prompt_filename(record.get("dispatch_id")),
    }


def _empty_payload() -> dict[str, object]:
    return {"schema": HISTORY_SCHEMA, "updated_at": None, "projects": []}


def _json_for_script(payload: object) -> str:
    return (
        json.dumps(payload, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("&", "\\u0026")
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )


def _read_payload(path: Path) -> dict[str, object]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return _empty_payload()
    if not text.startswith(_SCRIPT_PREFIX) or not text.endswith(";\n"):
        return _empty_payload()
    try:
        payload = json.loads(text[len(_SCRIPT_PREFIX) : -2])
    except (TypeError, ValueError, json.JSONDecodeError):
        return _empty_payload()
    if not isinstance(payload, dict) or payload.get("schema") != HISTORY_SCHEMA:
        return _empty_payload()
    if not isinstance(payload.get("projects"), list):
        return _empty_payload()
    return payload


def _publish(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = _SCRIPT_PREFIX + _json_for_script(payload) + ";\n"
    temp_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False
        ) as handle:
            temp_name = handle.name
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, path)
    except BaseException:
        # Cleanup must cover interrupts too (a KeyboardInterrupt mid-write
        # otherwise strands the temp file forever); the error still raises.
        if temp_name:
            with contextlib.suppress(OSError):
                Path(temp_name).unlink()
        raise


class _HistoryLock:
    def __init__(self, output_dir: Path) -> None:
        self.path = output_dir / ".history-data.lock"
        self.handle = None

    def __enter__(self) -> "_HistoryLock":
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.handle = self.path.open("a+", encoding="utf-8")
        fcntl.flock(self.handle, fcntl.LOCK_EX)
        return self

    def __exit__(self, *_exc: object) -> None:
        if self.handle is not None:
            fcntl.flock(self.handle, fcntl.LOCK_UN)
            self.handle.close()


class _CatchUpLock:
    """Keep recovery sweeps singular without blocking the fast-plane lock."""

    def __init__(self, output_dir: Path) -> None:
        self.path = output_dir / ".history-catchup.lock"
        self.handle = None

    def __enter__(self) -> bool:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        handle = self.path.open("a+", encoding="utf-8")
        try:
            fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except OSError as exc:
            handle.close()
            if exc.errno in {errno.EACCES, errno.EAGAIN}:
                return False
            raise
        self.handle = handle
        return True

    def __exit__(self, *_exc: object) -> None:
        if self.handle is not None:
            fcntl.flock(self.handle, fcntl.LOCK_UN)
            self.handle.close()
            self.handle = None


def project_prompt(record: dict, *, output_dir: Path | None = None) -> bool:
    resolved = _resolved_output_dir(output_dir)
    filename = prompt_filename(record.get("dispatch_id"))
    prompt_path = record.get("prompt_path")
    if resolved is None or filename is None or not isinstance(prompt_path, str) or not prompt_path:
        return False
    target = resolved / "prompts" / filename
    if target.exists():
        return False
    try:
        text = Path(prompt_path).expanduser().read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    try:
        descriptor = os.open(target, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError:
        return False
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
    except BaseException:
        with contextlib.suppress(OSError):
            target.unlink()
        raise
    return True


def project_terminals(
    records: Iterable[dict], *, output_dir: Path | None = None
) -> int:
    resolved = _resolved_output_dir(output_dir)
    if resolved is None:
        return 0
    rows: list[tuple[str, str, dict[str, object]]] = []
    for record in records:
        if (
            not isinstance(record, dict)
            or not _is_terminal(record)
            or not record.get("dispatch_id")
        ):
            continue
        pid = project_id(record.get("project_root"))
        name = (
            _display(
                Path(str(record.get("project_root") or "unknown")).name,
                limit=64,
            )
            or "project"
        )
        row = history_worker_row(record)
        if not isinstance(row.get("dispatch_id"), str):
            continue
        rows.append((pid, name, row))
    if not rows:
        return 0

    target = resolved / "history-data.js"
    projected = 0
    with _HistoryLock(resolved):
        payload = _read_payload(target)
        raw_projects = payload.get("projects")
        projects = (
            [item for item in raw_projects if isinstance(item, dict)]
            if isinstance(raw_projects, list)
            else []
        )
        by_project = {str(item.get("project_id") or ""): item for item in projects}
        changed_projects: set[str] = set()
        known_dispatches: dict[str, set[str]] = {}
        for pid, name, row in rows:
            project = by_project.get(pid)
            if project is None:
                project = {"project_id": pid, "name": name, "workers": []}
                projects.append(project)
                by_project[pid] = project
            raw_workers = project.get("workers")
            workers = (
                [item for item in raw_workers if isinstance(item, dict)]
                if isinstance(raw_workers, list)
                else []
            )
            dispatches = known_dispatches.setdefault(
                pid,
                {
                    item["dispatch_id"]
                    for item in workers
                    if isinstance(item.get("dispatch_id"), str)
                },
            )
            dispatch_id = row.get("dispatch_id")
            assert isinstance(dispatch_id, str)
            if dispatch_id in dispatches:
                continue
            workers.append(row)
            project["workers"] = workers
            dispatches.add(dispatch_id)
            changed_projects.add(pid)
            projected += 1
        if not projected:
            return 0
        for pid in changed_projects:
            workers = by_project[pid]["workers"]
            assert isinstance(workers, list)
            workers.sort(
                key=lambda item: (
                    str(item.get("ended_at") or item.get("started_at") or ""),
                    str(item.get("dispatch_id") or ""),
                ),
                reverse=True,
            )
        projects.sort(key=lambda item: str(item.get("project_id") or ""))
        payload = {
            "schema": HISTORY_SCHEMA,
            "updated_at": utc_now(),
            "projects": projects,
        }
        _publish(target, payload)
    return projected


def project_terminal(record: dict, *, output_dir: Path | None = None) -> bool:
    return bool(project_terminals((record,), output_dir=output_dir))


def catch_up(
    records: Iterable[dict], *, output_dir: Path | None = None
) -> dict[str, int]:
    record_list = [record for record in records if isinstance(record, dict)]
    projected_prompts = 0
    for record in record_list:
        projected_prompts += int(project_prompt(record, output_dir=output_dir))
    projected_history = project_terminals(record_list, output_dir=output_dir)
    return {"prompts": projected_prompts, "history": projected_history}


def catch_up_if_due(
    records_loader: Callable[[], Iterable[dict]],
    *,
    output_dir: Path | None = None,
    now: Callable[[], float] = time.time,
    interval_s: float = CATCH_UP_INTERVAL_S,
) -> dict[str, int] | None:
    resolved = _resolved_output_dir(output_dir)
    if resolved is None:
        return None
    with _CatchUpLock(resolved) as acquired:
        if not acquired:
            return None
        stamp = resolved / ".history-catchup"
        try:
            last = stamp.stat().st_mtime
        except OSError:
            last = 0.0
        current = now()
        if current - last < interval_s:
            return None
        result = catch_up(records_loader(), output_dir=resolved)
        stamp.parent.mkdir(parents=True, exist_ok=True)
        stamp.touch()
        return result
