#!/usr/bin/env bash
# install-codex-overrides.sh — register a project as codex-trusted so non-
# interactive `codex exec` dispatches bypass MCP tool approval gates.
#
# Background
# ----------
# When `~/.codex/config.toml` declares an MCP server (e.g. context-mode) with
# per-tool `approval_mode = "approve"`, `codex exec` (non-interactive, no TTY)
# blocks forever on the first MCP tool call — the model invokes the tool,
# codex waits for an approval click that has no surface to arrive on, and the
# dispatch hangs with zero-byte output. This is the ~2/5 silent-stall failure
# mode that goal-flight controllers were hitting.
#
# Fix: codex auto-approves trusted projects' MCP calls when the cwd at exec
# time is inside a project registered as:
#
#   [projects."<ABSOLUTE_PATH>"]
#   trust_level = "trusted"
#
# in `~/.codex/config.toml`. Path matching is prefix-based, so `.claude/
# worktrees/*` and any other subdirectory inherits trust from the project
# root — no per-worktree registration needed.
#
# What this script does
# ---------------------
# 1. Idempotently adds the trust block for <project root> to `~/.codex/config.toml`.
# 2. Optionally mirrors it to `<project>/.codex/config.toml` (self-documenting,
#    survives a future `~/.codex/` rebuild). Defaults on; suppress with --no-project-mirror.
# 3. Echoes a verification block.
#
# Usage
# -----
#   install-codex-overrides.sh                  # detect project root from cwd (git toplevel)
#   install-codex-overrides.sh <path>           # explicit project root
#   install-codex-overrides.sh --check          # report state, write nothing
#   install-codex-overrides.sh --no-project-mirror   # skip writing <project>/.codex/config.toml
#
# Re-running is safe — entries are appended only if not already present.
#
# After install: codex exec dispatches in this project (including from worktrees)
# can use MCP tools without stalling. Recommended dispatch shape (preserves the
# hard wall-clock ceiling — codex v0.130.0 has no --timeout flag):
#
#   timeout --kill-after=10 300 codex exec '<prompt>' > <tail> 2>&1 &

set -euo pipefail

CHECK_ONLY=0
WRITE_PROJECT_MIRROR=1
PROJECT_ROOT=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --check) CHECK_ONLY=1 ;;
    --no-project-mirror) WRITE_PROJECT_MIRROR=0 ;;
    -h|--help) sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) PROJECT_ROOT="$1" ;;
  esac
  shift
done

# Detect project root if not explicit
if [ -z "$PROJECT_ROOT" ]; then
  PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
fi
PROJECT_ROOT="$(cd "$PROJECT_ROOT" && pwd)"

USER_CONFIG="$HOME/.codex/config.toml"
PROJECT_CONFIG="$PROJECT_ROOT/.codex/config.toml"
ENTRY_KEY="[projects.\"${PROJECT_ROOT}\"]"

# --- 1. User config ---

if [ ! -f "$USER_CONFIG" ]; then
  if [ "$CHECK_ONLY" -eq 1 ]; then
    echo "CHECK: $USER_CONFIG does not exist."
    exit 1
  fi
  mkdir -p "$(dirname "$USER_CONFIG")"
  : > "$USER_CONFIG"
fi

if grep -qF "$ENTRY_KEY" "$USER_CONFIG"; then
  echo "user config:    already trusts ${PROJECT_ROOT}"
elif [ "$CHECK_ONLY" -eq 1 ]; then
  echo "CHECK: user config does NOT trust ${PROJECT_ROOT}"
  exit 1
else
  # Ensure file ends with newline before appending
  if [ -s "$USER_CONFIG" ] && [ "$(tail -c1 "$USER_CONFIG" | wc -l | tr -d ' ')" != "1" ]; then
    printf '\n' >> "$USER_CONFIG"
  fi
  printf '\n%s\ntrust_level = "trusted"\n' "$ENTRY_KEY" >> "$USER_CONFIG"
  echo "user config:    appended trust entry for ${PROJECT_ROOT}"
fi

# --- 2. Project mirror ---

if [ "$WRITE_PROJECT_MIRROR" -eq 1 ] && [ "$CHECK_ONLY" -eq 0 ]; then
  mkdir -p "$PROJECT_ROOT/.codex"
  if [ ! -f "$PROJECT_CONFIG" ]; then
    cat > "$PROJECT_CONFIG" <<EOF
# Project-scoped codex settings.
#
# The [projects.<abs>] block declares this project as trusted, which bypasses
# [mcp_servers.X.tools.Y].approval_mode = "approve" entries in user config
# that would otherwise block non-interactive codex exec dispatches on the
# first MCP tool call. Worktrees under <project>/.claude/worktrees/ inherit
# trust via path prefix-matching.
#
# Generated by goal-flight's scripts/install-codex-overrides.sh.
# Re-run that script to refresh. Consider adding .codex/ to .gitignore if
# this file's absolute paths shouldn't be shared across machines.
approval_policy = "on-request"
sandbox_mode = "workspace-write"

${ENTRY_KEY}
trust_level = "trusted"
EOF
    echo "project config: wrote ${PROJECT_CONFIG}"
  elif grep -qF "$ENTRY_KEY" "$PROJECT_CONFIG"; then
    echo "project config: ${PROJECT_CONFIG} already has trust entry"
  else
    if [ "$(tail -c1 "$PROJECT_CONFIG" | wc -l | tr -d ' ')" != "1" ]; then
      printf '\n' >> "$PROJECT_CONFIG"
    fi
    printf '\n%s\ntrust_level = "trusted"\n' "$ENTRY_KEY" >> "$PROJECT_CONFIG"
    echo "project config: appended trust entry to ${PROJECT_CONFIG}"
  fi
fi

# --- 3. Verify ---

echo
echo "=== verify ==="
grep -A1 -F "$ENTRY_KEY" "$USER_CONFIG" || echo "MISSING from $USER_CONFIG"
echo
echo "Worktrees under ${PROJECT_ROOT}/.claude/worktrees/ inherit trust via path prefix."
echo "Done."
